import type { ProblemSeed, TopicSeed } from "./types.js";

export const topicSeeds: TopicSeed[] = [
  {
    name: "Foundation",
    slug: "foundation",
    order: 1,
    targetCount: 46,
    description: "Time complexity, STL, math, recursion, and core problem solving basics.",
    accent: "#7dd3fc",
  },
  {
    name: "Arrays",
    slug: "arrays",
    order: 2,
    targetCount: 45,
    description: "Classic array problems, patterns, and foundational interview questions.",
    accent: "#fda4af",
  },
  {
    name: "Strings",
    slug: "strings",
    order: 3,
    targetCount: 35,
    description: "String manipulation, parsing, frequency tricks, and pattern matching.",
    accent: "#86efac",
  },
  {
    name: "Hashing",
    slug: "hashing",
    order: 4,
    targetCount: 20,
    description: "Maps, sets, frequency tables, and lookup-based optimization.",
    accent: "#f9a8d4",
  },
  {
    name: "Two Pointers",
    slug: "two-pointers",
    order: 5,
    targetCount: 20,
    description: "Left-right scanning, pair matching, and range optimization.",
    accent: "#fdba74",
  },
  {
    name: "Sliding Window",
    slug: "sliding-window",
    order: 6,
    targetCount: 25,
    description: "Window-based counting, subarray optimization, and frequency updates.",
    accent: "#c4b5fd",
  },
  {
    name: "Binary Search",
    slug: "binary-search",
    order: 7,
    targetCount: 35,
    description: "Binary search on arrays, answer space, and monotonic conditions.",
    accent: "#93c5fd",
  },
  {
    name: "Linked List",
    slug: "linked-list",
    order: 8,
    targetCount: 36,
    description: "Single and doubly linked list patterns, reversals, and cycle logic.",
    accent: "#67e8f9",
  },
  {
    name: "Stack",
    slug: "stack",
    order: 9,
    targetCount: 30,
    description: "Stack usage, monotonic stack, parsing, and expression logic.",
    accent: "#fcd34d",
  },
  {
    name: "Queue",
    slug: "queue",
    order: 10,
    targetCount: 15,
    description: "Queue patterns, deque usage, and task scheduling ideas.",
    accent: "#a7f3d0",
  },
  {
    name: "Trees",
    slug: "trees",
    order: 11,
    targetCount: 60,
    description: "Traversals, recursion, diameter, views, and tree DP basics.",
    accent: "#fde68a",
  },
  {
    name: "Binary Search Tree (BST)",
    slug: "bst",
    order: 12,
    targetCount: 25,
    description: "BST search, insertion, deletion, and validation patterns.",
    accent: "#fca5a5",
  },
  {
    name: "Heap / Priority Queue",
    slug: "heap-priority-queue",
    order: 13,
    targetCount: 25,
    description: "Top-k, selection, merging, and priority-driven decisions.",
    accent: "#c084fc",
  },
  {
    name: "Graph",
    slug: "graph",
    order: 14,
    targetCount: 70,
    description: "Traversal, shortest path, topological sorting, and DSU.",
    accent: "#60a5fa",
  },
  {
    name: "Greedy",
    slug: "greedy",
    order: 15,
    targetCount: 35,
    description: "Local choice reasoning, scheduling, and exchange arguments.",
    accent: "#34d399",
  },
  {
    name: "Backtracking",
    slug: "backtracking",
    order: 16,
    targetCount: 25,
    description: "Enumerating possibilities with pruning and recursion trees.",
    accent: "#fb7185",
  },
  {
    name: "Trie",
    slug: "trie",
    order: 17,
    targetCount: 15,
    description: "Prefix trees, word search, and dictionary-style lookups.",
    accent: "#22c55e",
  },
  {
    name: "Dynamic Programming",
    slug: "dynamic-programming",
    order: 18,
    targetCount: 80,
    description: "Recurrence patterns, memoization, tabulation, and optimization.",
    accent: "#818cf8",
  },
  {
    name: "Bit Manipulation",
    slug: "bit-manipulation",
    order: 19,
    targetCount: 25,
    description: "Bit tricks, masks, subset logic, and XOR reasoning.",
    accent: "#38bdf8",
  },
  {
    name: "Segment Tree & Fenwick Tree",
    slug: "segment-tree-fenwick-tree",
    order: 20,
    targetCount: 15,
    description: "Range queries, updates, and advanced logarithmic structures.",
    accent: "#f472b6",
  },
];

const leetcode = (slug: string) => `https://leetcode.com/problems/${slug}/`;

const roadmapForTopic = (
  topicSlug: string,
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
): ProblemSeed[] =>
  entries.map((entry) => ({
    ...entry,
    topicSlug,
    roadmapSection,
    roadmapSectionOrder,
  }));

const arraysRoadmap = (
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
) => roadmapForTopic("arrays", roadmapSection, roadmapSectionOrder, entries);

const stringsRoadmap = (
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
) => roadmapForTopic("strings", roadmapSection, roadmapSectionOrder, entries);

const hashingRoadmap = (
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
) => roadmapForTopic("hashing", roadmapSection, roadmapSectionOrder, entries);

const twoPointersRoadmap = (
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
) => roadmapForTopic("two-pointers", roadmapSection, roadmapSectionOrder, entries);

export const problemSeeds: ProblemSeed[] = [
  ...arraysRoadmap("Basic Arrays", 1, [
    {
      roadmapOrder: 1,
      title: "Largest Element",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/largest-element-in-array4009/1",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 7,
      shortNote: "Single pass tracking current maximum.",
      longNote: "Traverse once and keep the largest value seen so far.",
      tags: ["arrays", "traversal"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Second Largest Element",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/second-largest3735/1",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 8,
      shortNote: "Track largest and second largest together.",
      longNote: "Maintain top two distinct values during one traversal.",
      tags: ["arrays", "traversal"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Check if Array is Sorted",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 6,
      shortNote: "Compare every pair of adjacent elements.",
      longNote: "The first decreasing adjacent pair proves the array is not sorted.",
      tags: ["arrays", "traversal"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Remove Duplicates from Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("remove-duplicates-from-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 9,
      shortNote: "Use a write pointer for the next unique slot.",
      longNote: "Scan with one pointer and write each new unique value in place.",
      tags: ["arrays", "two pointers", "in-place"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Rotate Array",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Reversal",
      rating: 9,
      shortNote: "Reverse whole array, then reverse both parts.",
      longNote: "Normalize k and use three reversals for an in-place rotate.",
      tags: ["arrays", "reversal"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Move Zeroes",
      platformName: "LeetCode",
      platformUrl: leetcode("move-zeroes"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 10,
      shortNote: "Compact non-zero values first, zero-fill the rest.",
      longNote: "Keep a write pointer for non-zero elements and preserve their order.",
      tags: ["arrays", "two pointers", "in-place"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 7,
      title: "Missing Number",
      platformName: "LeetCode",
      platformUrl: leetcode("missing-number"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Math/XOR",
      rating: 9,
      shortNote: "Solve via xor cancellation or expected sum difference.",
      longNote: "Use xor of indices and values, or compare sum(0..n) against array sum.",
      tags: ["arrays", "math", "xor"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Union of Two Arrays",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/union-of-two-arrays3538/1",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing",
      rating: 8,
      shortNote: "Use a set to count unique values across both arrays.",
      longNote: "Insert all values into a hash set and return its size or contents.",
      tags: ["arrays", "hashing", "set"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Intersection of Two Arrays",
      platformName: "LeetCode",
      platformUrl: leetcode("intersection-of-two-arrays"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing",
      rating: 8,
      shortNote: "Store one array in a set and collect common values.",
      longNote: "Use hashing to test membership and avoid duplicate output values.",
      tags: ["arrays", "hashing", "set"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Two Pointer", 2, [
    {
      roadmapOrder: 1,
      title: "Two Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("two-sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 10,
      shortNote: "Check complement before storing current number.",
      longNote: "One-pass hash map gives O(n) time and tracks previous complements.",
      tags: ["arrays", "hash map"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Container With Most Water",
      platformName: "LeetCode",
      platformUrl: leetcode("container-with-most-water"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Two Pointer",
      rating: 10,
      shortNote: "Move the shorter wall inward greedily.",
      longNote: "Area is width times min height, so only moving the shorter side can help.",
      tags: ["arrays", "two pointers", "greedy"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "3Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("3sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sorting + Two Pointer",
      rating: 10,
      shortNote: "Sort, fix one value, and run two pointers on the suffix.",
      longNote: "Skip duplicates carefully and use left/right movement based on the current sum.",
      tags: ["arrays", "sorting", "two pointers"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "4Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("4sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sorting",
      rating: 8,
      shortNote: "Sort, fix two values, and solve remaining pair with two pointers.",
      longNote: "Prune duplicates and be careful about overflow while comparing sums.",
      tags: ["arrays", "sorting", "two pointers"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Sort Colors",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-colors"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "DNF",
      rating: 10,
      shortNote: "Use low, mid, high pointers for Dutch National Flag.",
      longNote: "Partition the array into 0s, 1s, and 2s in one pass.",
      tags: ["arrays", "dnf", "two pointers"],
      priority: 10,
      isPinned: true,
    },
  ]),
  ...arraysRoadmap("Sliding Window", 3, [
    {
      roadmapOrder: 1,
      title: "Longest Substring Without Repeating Characters",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-substring-without-repeating-characters"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Track last seen positions and tighten the window on repeats.",
      longNote: "Maintain a left boundary that jumps past the previous occurrence of each character.",
      tags: ["arrays", "sliding window", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Minimum Size Subarray Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-size-subarray-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 9,
      shortNote: "Expand to satisfy the sum, then shrink greedily.",
      longNote: "For positive numbers, a variable window gives the shortest valid segment.",
      tags: ["arrays", "sliding window"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Minimum Window Substring",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-window-substring"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Track required counts and shrink once the window is valid.",
      longNote: "Use frequency maps plus a matched counter to find the minimum valid window.",
      tags: ["arrays", "sliding window", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Maximum Average Subarray",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-average-subarray-i"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 7,
      shortNote: "Keep a fixed-size rolling sum.",
      longNote: "Subtract outgoing values and add incoming values while tracking the best sum.",
      tags: ["arrays", "sliding window"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Permutation in String",
      platformName: "LeetCode",
      platformUrl: leetcode("permutation-in-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 8,
      shortNote: "Compare window frequencies against target frequencies.",
      longNote: "Fixed-size window over s2 with character counts detects any permutation of s1.",
      tags: ["arrays", "sliding window", "frequency"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Prefix Sum", 4, [
    {
      roadmapOrder: 1,
      title: "Product of Array Except Self",
      platformName: "LeetCode",
      platformUrl: leetcode("product-of-array-except-self"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix",
      rating: 10,
      shortNote: "Combine prefix and suffix products without division.",
      longNote: "Build left products first, then multiply by a rolling right product.",
      tags: ["arrays", "prefix", "suffix"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Subarray Sum Equals K",
      platformName: "LeetCode",
      platformUrl: leetcode("subarray-sum-equals-k"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix+HashMap",
      rating: 10,
      shortNote: "Count previous prefix sums equal to current minus k.",
      longNote: "A hash map of prefix frequencies turns subarray counting into O(n).",
      tags: ["arrays", "prefix sum", "hash map"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Range Sum Query",
      platformName: "LeetCode",
      platformUrl: leetcode("range-sum-query-immutable"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Prefix",
      rating: 7,
      shortNote: "Precompute prefix sums for O(1) range queries.",
      longNote: "Store cumulative sums so any [l, r] total is prefix[r+1] - prefix[l].",
      tags: ["arrays", "prefix sum"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Pivot Index",
      platformName: "LeetCode",
      platformUrl: leetcode("find-pivot-index"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Prefix",
      rating: 7,
      shortNote: "Compare left sum with total minus left sum minus current value.",
      longNote: "A rolling left sum is enough once total sum is known.",
      tags: ["arrays", "prefix sum"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Continuous Subarray Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("continuous-subarray-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix",
      rating: 8,
      shortNote: "Track prefix remainders modulo k and earliest positions.",
      longNote: "If the same remainder reappears with distance > 1, the subarray sum is a multiple of k.",
      tags: ["arrays", "prefix sum", "modulo"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Kadane", 5, [
    {
      roadmapOrder: 1,
      title: "Maximum Subarray",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-subarray"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Kadane",
      rating: 10,
      shortNote: "Either extend the current sum or restart from the current element.",
      longNote: "Kadane's algorithm keeps the best running segment ending at each position.",
      tags: ["arrays", "kadane", "dp"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Maximum Circular Subarray",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-sum-circular-subarray"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Kadane",
      rating: 8,
      shortNote: "Best answer is max normal subarray or total minus min subarray.",
      longNote: "Run Kadane twice for max and min subarray, while handling all-negative arrays.",
      tags: ["arrays", "kadane", "circular"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Matrix", 6, [
    {
      roadmapOrder: 1,
      title: "Rotate Image",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-image"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Matrix",
      rating: 10,
      shortNote: "Transpose first, then reverse each row.",
      longNote: "The 90-degree clockwise rotation is an in-place transpose plus row reversal.",
      tags: ["arrays", "matrix"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Set Matrix Zeroes",
      platformName: "LeetCode",
      platformUrl: leetcode("set-matrix-zeroes"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Matrix",
      rating: 10,
      shortNote: "Use first row and column as markers.",
      longNote: "Track whether the first row or first column should be zeroed separately.",
      tags: ["arrays", "matrix", "in-place"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Spiral Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("spiral-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Simulation",
      rating: 9,
      shortNote: "Shrink top, right, bottom, and left boundaries layer by layer.",
      longNote: "Traverse one perimeter at a time and tighten bounds after each side.",
      tags: ["arrays", "matrix", "simulation"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Search 2D Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("search-a-2d-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Treat the matrix like a flattened sorted array.",
      longNote: "Binary search over [0, m*n) and map each index back to row/column.",
      tags: ["arrays", "matrix", "binary search"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Binary Search on Arrays", 7, [
    {
      roadmapOrder: 1,
      title: "Binary Search",
      platformName: "LeetCode",
      platformUrl: leetcode("binary-search"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 10,
      shortNote: "Use the standard low/high midpoint template.",
      longNote: "Maintain a valid search interval and shrink it based on midpoint comparison.",
      tags: ["arrays", "binary search"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Search Insert Position",
      platformName: "LeetCode",
      platformUrl: leetcode("search-insert-position"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Find the first position where target can be placed.",
      longNote: "Lower-bound style binary search returns the insertion index.",
      tags: ["arrays", "binary search"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Search in Rotated Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("search-in-rotated-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 10,
      shortNote: "Detect which half is sorted, then decide where target lies.",
      longNote: "One side of the midpoint is always sorted; use that to discard half the range.",
      tags: ["arrays", "binary search", "rotated array"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Find Minimum in Rotated Array",
      platformName: "LeetCode",
      platformUrl: leetcode("find-minimum-in-rotated-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 9,
      shortNote: "Compare midpoint with right boundary to find the pivot side.",
      longNote: "The unsorted half contains the minimum, so shrink toward it.",
      tags: ["arrays", "binary search", "rotated array"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Find Peak Element",
      platformName: "LeetCode",
      platformUrl: leetcode("find-peak-element"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Move toward the neighbor that is larger.",
      longNote: "A rising slope guarantees a peak ahead, so binary search on slope direction works.",
      tags: ["arrays", "binary search"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...arraysRoadmap("Greedy & Advanced", 8, [
    {
      roadmapOrder: 1,
      title: "Best Time to Buy and Sell Stock",
      platformName: "LeetCode",
      platformUrl: leetcode("best-time-to-buy-and-sell-stock"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Greedy",
      rating: 10,
      shortNote: "Track the minimum buy price and best profit so far.",
      longNote: "Every day is a sell candidate after the cheapest previous buy day.",
      tags: ["arrays", "greedy"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Jump Game",
      platformName: "LeetCode",
      platformUrl: leetcode("jump-game"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Greedy",
      rating: 10,
      shortNote: "Keep the farthest reachable index while scanning.",
      longNote: "If the current index ever exceeds reach, the end is impossible.",
      tags: ["arrays", "greedy"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Jump Game II",
      platformName: "LeetCode",
      platformUrl: leetcode("jump-game-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Greedy",
      rating: 9,
      shortNote: "Expand the current range and jump when the range ends.",
      longNote: "Layered greedy traversal gives the minimum jumps in O(n).",
      tags: ["arrays", "greedy"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Merge Intervals",
      platformName: "LeetCode",
      platformUrl: leetcode("merge-intervals"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Intervals",
      rating: 10,
      shortNote: "Sort by start and merge overlapping ranges.",
      longNote: "Maintain a running interval and extend it while overlaps continue.",
      tags: ["arrays", "intervals", "sorting"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "Insert Interval",
      platformName: "LeetCode",
      platformUrl: leetcode("insert-interval"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Intervals",
      rating: 8,
      shortNote: "Append non-overlapping intervals, merge overlaps, then append the rest.",
      longNote: "Only the intervals intersecting the new range need to be merged.",
      tags: ["arrays", "intervals"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "First Missing Positive",
      platformName: "LeetCode",
      platformUrl: leetcode("first-missing-positive"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Index Placement",
      rating: 9,
      shortNote: "Place each value x at index x-1 when possible.",
      longNote: "Cyclic placement reveals the first index whose value is incorrect.",
      tags: ["arrays", "cyclic sort", "index placement"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Trapping Rain Water",
      platformName: "LeetCode",
      platformUrl: leetcode("trapping-rain-water"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Two Pointer",
      rating: 10,
      shortNote: "Move the side with smaller max boundary inward.",
      longNote: "Water level at each step is limited by the smaller side's running maximum.",
      tags: ["arrays", "two pointers"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "Largest Rectangle in Histogram",
      platformName: "LeetCode",
      platformUrl: leetcode("largest-rectangle-in-histogram"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Monotonic Stack",
      rating: 10,
      shortNote: "Use an increasing stack to compute width on every pop.",
      longNote: "Each bar becomes the limiting height when a smaller bar appears.",
      tags: ["arrays", "monotonic stack"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 9,
      title: "Sliding Window Maximum",
      platformName: "LeetCode",
      platformUrl: leetcode("sliding-window-maximum"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Deque",
      rating: 10,
      shortNote: "Maintain a decreasing deque of candidate indices.",
      longNote: "Pop smaller tail elements and remove indices that leave the window.",
      tags: ["arrays", "deque", "sliding window"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 10,
      title: "Median of Two Sorted Arrays",
      platformName: "LeetCode",
      platformUrl: leetcode("median-of-two-sorted-arrays"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 9,
      shortNote: "Binary search the partition on the smaller array.",
      longNote: "Find partitions where left halves are <= right halves and derive the median.",
      tags: ["arrays", "binary search"],
      priority: 9,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("String Basics", 1, [
    {
      roadmapOrder: 1,
      title: "Reverse String",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 8,
      shortNote: "Swap from both ends moving inward.",
      longNote: "A classic in-place two-pointer reversal over a character array.",
      tags: ["strings", "two pointers"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Reverse Words in a String",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-words-in-a-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Simulation",
      rating: 8,
      shortNote: "Trim spaces, split words, and rebuild in reverse order.",
      longNote: "Handle extra spaces carefully and reconstruct the sentence word by word.",
      tags: ["strings", "simulation"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Valid Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 9,
      shortNote: "Skip non-alphanumeric chars while comparing both ends.",
      longNote: "Normalize case and move pointers inward while ignoring punctuation.",
      tags: ["strings", "two pointers", "palindrome"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Valid Anagram",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-anagram"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing",
      rating: 9,
      shortNote: "Compare character frequency counts.",
      longNote: "Use a fixed-size frequency array or map depending on character set.",
      tags: ["strings", "hashing", "frequency"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Longest Common Prefix",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-common-prefix"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "String Traversal",
      rating: 8,
      shortNote: "Scan character by character across all strings.",
      longNote: "Stop at the first mismatch or string boundary to get the prefix length.",
      tags: ["strings", "traversal"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Isomorphic Strings",
      platformName: "LeetCode",
      platformUrl: leetcode("isomorphic-strings"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Maintain forward and reverse mappings simultaneously.",
      longNote: "Bijective mapping is required, so validate both directions together.",
      tags: ["strings", "hash map"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Roman to Integer",
      platformName: "LeetCode",
      platformUrl: leetcode("roman-to-integer"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Parsing",
      rating: 7,
      shortNote: "Subtract when a smaller value appears before a larger one.",
      longNote: "Scan left to right or right to left while handling subtractive pairs.",
      tags: ["strings", "parsing"],
      priority: 7,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("Hashing & Frequency", 2, [
    {
      roadmapOrder: 1,
      title: "Group Anagrams",
      platformName: "LeetCode",
      platformUrl: leetcode("group-anagrams"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 10,
      shortNote: "Use sorted string or frequency signature as the key.",
      longNote: "Map each canonical form to the list of strings sharing it.",
      tags: ["strings", "hash map", "anagram"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "First Unique Character",
      platformName: "LeetCode",
      platformUrl: leetcode("first-unique-character-in-a-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Frequency Count",
      rating: 8,
      shortNote: "Count frequencies first, then scan for the first count of one.",
      longNote: "A two-pass solution is simple and avoids extra index bookkeeping.",
      tags: ["strings", "frequency"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Find All Anagrams in a String",
      platformName: "LeetCode",
      platformUrl: leetcode("find-all-anagrams-in-a-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window + Hashing",
      rating: 9,
      shortNote: "Compare fixed-size window counts against the target counts.",
      longNote: "Maintain a rolling frequency window equal to pattern length.",
      tags: ["strings", "sliding window", "hashing"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Ransom Note",
      platformName: "LeetCode",
      platformUrl: leetcode("ransom-note"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Frequency Count",
      rating: 7,
      shortNote: "Magazine counts must cover every note character.",
      longNote: "Subtract note frequencies from magazine frequencies and detect deficits.",
      tags: ["strings", "frequency"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Word Pattern",
      platformName: "LeetCode",
      platformUrl: leetcode("word-pattern"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Validate a bijection between pattern chars and words.",
      longNote: "Store both char->word and word->char to enforce one-to-one mapping.",
      tags: ["strings", "hash map"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Sort Characters by Frequency",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-characters-by-frequency"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map + Sorting",
      rating: 8,
      shortNote: "Count chars and sort them by descending frequency.",
      longNote: "Bucket sort or standard sorting both work depending on constraints.",
      tags: ["strings", "hash map", "sorting"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("Sliding Window", 3, [
    {
      roadmapOrder: 1,
      title: "Longest Substring Without Repeating Characters",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-substring-without-repeating-characters"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Use last seen indices to keep the window duplicate-free.",
      longNote: "Move the left boundary past repeated characters without shrinking one step at a time.",
      tags: ["strings", "sliding window", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Longest Repeating Character Replacement",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-repeating-character-replacement"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Window is valid while replacements needed stay within k.",
      longNote: "Track max frequency in the window and shrink when windowSize - maxFreq exceeds k.",
      tags: ["strings", "sliding window"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Permutation in String",
      platformName: "LeetCode",
      platformUrl: leetcode("permutation-in-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 9,
      shortNote: "Look for any fixed-size window matching target frequencies.",
      longNote: "Slide a window of length s1 and compare the rolling character counts.",
      tags: ["strings", "sliding window", "frequency"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Minimum Window Substring",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-window-substring"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Shrink only after all required chars are covered.",
      longNote: "Maintain required counts and a matched counter to detect valid windows.",
      tags: ["strings", "sliding window", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "Longest Substring with At Most K Distinct",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-substring-with-at-most-k-distinct-characters"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 9,
      shortNote: "Shrink once distinct character count exceeds k.",
      longNote: "A frequency map makes it easy to add and remove characters as the window moves.",
      tags: ["strings", "sliding window", "hash map"],
      priority: 9,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("Palindrome", 4, [
    {
      roadmapOrder: 1,
      title: "Longest Palindromic Substring",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-palindromic-substring"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Expand Around Center",
      rating: 10,
      shortNote: "Expand from both odd and even centers.",
      longNote: "Every palindrome grows from a center, so try both center shapes at each index.",
      tags: ["strings", "palindrome"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Palindromic Substrings",
      platformName: "LeetCode",
      platformUrl: leetcode("palindromic-substrings"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Expand Around Center",
      rating: 9,
      shortNote: "Count palindromes while expanding from every center.",
      longNote: "Each successful expansion contributes one valid palindromic substring.",
      tags: ["strings", "palindrome"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Valid Palindrome II",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome-ii"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 8,
      shortNote: "At the first mismatch, try skipping either side once.",
      longNote: "A helper palindrome check after one deletion handles the only branching point.",
      tags: ["strings", "palindrome", "two pointers"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Shortest Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("shortest-palindrome"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "KMP",
      rating: 8,
      shortNote: "Use LPS on s + separator + reverse(s) to find the longest palindromic prefix.",
      longNote: "The unmatched suffix can be reversed and prepended once the prefix length is known.",
      tags: ["strings", "kmp", "palindrome"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Break a Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("break-a-palindrome"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Greedy",
      rating: 7,
      shortNote: "Change the first non-'a' in the first half, otherwise change the last char.",
      longNote: "Lexicographic minimum comes from the earliest beneficial change.",
      tags: ["strings", "greedy", "palindrome"],
      priority: 7,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("Pattern Matching", 5, [
    {
      roadmapOrder: 1,
      title: "Implement strStr()",
      platformName: "LeetCode",
      platformUrl: leetcode("find-the-index-of-the-first-occurrence-in-a-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "KMP",
      rating: 9,
      shortNote: "Use the LPS array to skip redundant comparisons.",
      longNote: "KMP avoids restarting from scratch after mismatches.",
      tags: ["strings", "kmp", "pattern matching"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Repeated Substring Pattern",
      platformName: "LeetCode",
      platformUrl: leetcode("repeated-substring-pattern"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "KMP",
      rating: 8,
      shortNote: "LPS reveals whether the string is built from a repeating block.",
      longNote: "A valid repeat exists if final LPS length divides the string appropriately.",
      tags: ["strings", "kmp"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "KMP Algorithm",
      platformName: "Theory",
      platformUrl: "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Pattern Matching",
      rating: 10,
      shortNote: "Build the LPS array to reuse matched prefix information.",
      longNote: "KMP preprocesses the pattern so mismatches jump to the next feasible prefix length.",
      tags: ["strings", "theory", "kmp"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Rabin-Karp Algorithm",
      platformName: "Theory",
      platformUrl: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Rolling Hash",
      rating: 9,
      shortNote: "Use rolling hash to compare substrings in amortized O(1).",
      longNote: "Hash matches need verification, but rolling updates make scanning fast in practice.",
      tags: ["strings", "theory", "rolling hash"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Z Algorithm",
      platformName: "Theory",
      platformUrl: "https://www.geeksforgeeks.org/z-algorithm-linear-time-pattern-searching-algorithm/",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Pattern Matching",
      rating: 8,
      shortNote: "Maintain a z-box to reuse previous match lengths.",
      longNote: "Z-values measure prefix matches from each index and support linear pattern searching.",
      tags: ["strings", "theory", "z algorithm"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap("Advanced", 6, [
    {
      roadmapOrder: 1,
      title: "Decode String",
      platformName: "LeetCode",
      platformUrl: leetcode("decode-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Stack",
      rating: 9,
      shortNote: "Push previous string and repeat count when entering brackets.",
      longNote: "On closing bracket, expand current segment and append it back to the parent context.",
      tags: ["strings", "stack"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "String Compression",
      platformName: "LeetCode",
      platformUrl: leetcode("string-compression"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 8,
      shortNote: "Read runs and write compressed output in place.",
      longNote: "A write pointer records chars and counts after each maximal run.",
      tags: ["strings", "two pointers", "in-place"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Multiply Strings",
      platformName: "LeetCode",
      platformUrl: leetcode("multiply-strings"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Math + String",
      rating: 9,
      shortNote: "Simulate grade-school multiplication into a digit array.",
      longNote: "Store partial sums by place value, then normalize carries at the end.",
      tags: ["strings", "math"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Text Justification",
      platformName: "LeetCode",
      platformUrl: leetcode("text-justification"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Simulation",
      rating: 8,
      shortNote: "Pack words greedily and distribute spaces per line.",
      longNote: "Handle single-word lines and the last line separately from full-justified lines.",
      tags: ["strings", "simulation"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Regular Expression Matching",
      platformName: "LeetCode",
      platformUrl: leetcode("regular-expression-matching"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Dynamic Programming",
      rating: 10,
      shortNote: "DP on indices with transitions for literal, dot, and star cases.",
      longNote: "The star branch either skips the pair or consumes a matching character.",
      tags: ["strings", "dp"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 6,
      title: "Wildcard Matching",
      platformName: "LeetCode",
      platformUrl: leetcode("wildcard-matching"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Dynamic Programming",
      rating: 9,
      shortNote: "DP handles '?' as one char and '*' as empty or many chars.",
      longNote: "Compress repeated stars if desired, then fill DP for all prefix pairs.",
      tags: ["strings", "dp"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Basic Calculator",
      platformName: "LeetCode",
      platformUrl: leetcode("basic-calculator"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Stack",
      rating: 9,
      shortNote: "Track current sign/result and push context at parentheses.",
      longNote: "Parentheses freeze the outer expression state until the inner result is complete.",
      tags: ["strings", "stack", "parsing"],
      priority: 9,
      isPinned: false,
    },
  ]),
  ...hashingRoadmap("Hash Set Basics", 1, [
    {
      roadmapOrder: 1,
      title: "Two Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("two-sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 10,
      shortNote: "Store seen numbers with their indices and look for complements.",
      longNote: "A one-pass hash map gives O(n) lookup for target - current.",
      tags: ["hashing", "hash map", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Contains Duplicate",
      platformName: "LeetCode",
      platformUrl: leetcode("contains-duplicate"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Set",
      rating: 9,
      shortNote: "Insert numbers into a set and detect repeats.",
      longNote: "A duplicate exists as soon as an insert target is already present in the set.",
      tags: ["hashing", "hash set"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Contains Duplicate II",
      platformName: "LeetCode",
      platformUrl: leetcode("contains-duplicate-ii"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Track the last index of each value.",
      longNote: "When a value repeats, compare current index with the previously stored index.",
      tags: ["hashing", "hash map"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Happy Number",
      platformName: "LeetCode",
      platformUrl: leetcode("happy-number"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Set",
      rating: 8,
      shortNote: "Use a set to detect cycles in the digit-square process.",
      longNote: "Repeated states imply a loop, and reaching 1 means the number is happy.",
      tags: ["hashing", "hash set", "math"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Intersection of Two Arrays",
      platformName: "LeetCode",
      platformUrl: leetcode("intersection-of-two-arrays"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Set",
      rating: 8,
      shortNote: "Store one array in a set and collect unique matches from the other.",
      longNote: "Hash-set lookup gives O(1) membership checks and avoids duplicate answers.",
      tags: ["hashing", "hash set", "arrays"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...hashingRoadmap("Frequency Counting", 2, [
    {
      roadmapOrder: 1,
      title: "Valid Anagram",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-anagram"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Frequency Count",
      rating: 9,
      shortNote: "Compare character counts between both strings.",
      longNote: "If every frequency matches, the two strings are valid anagrams.",
      tags: ["hashing", "frequency", "strings"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Majority Element",
      platformName: "LeetCode",
      platformUrl: leetcode("majority-element"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 10,
      shortNote: "Count frequencies and return the element crossing n/2.",
      longNote: "Hash-map counting is direct and easy to reason about, even though Boyer-Moore is optimal.",
      tags: ["hashing", "hash map", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Top K Frequent Elements",
      platformName: "LeetCode",
      platformUrl: leetcode("top-k-frequent-elements"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map + Heap",
      rating: 10,
      shortNote: "Count frequencies first, then extract top-k by heap or buckets.",
      longNote: "Frequency map plus heap gives a clean O(n log k) style solution.",
      tags: ["hashing", "heap", "frequency"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Sort Characters by Frequency",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-characters-by-frequency"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Count chars and sort them by descending frequency.",
      longNote: "After counting, rebuild the answer with the most frequent characters first.",
      tags: ["hashing", "frequency", "strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "First Unique Character",
      platformName: "LeetCode",
      platformUrl: leetcode("first-unique-character-in-a-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Frequency Count",
      rating: 8,
      shortNote: "Count first, then scan for the first char with count one.",
      longNote: "A two-pass frequency approach is simple and efficient.",
      tags: ["hashing", "frequency", "strings"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...hashingRoadmap("Prefix Sum + Hash Map", 3, [
    {
      roadmapOrder: 1,
      title: "Subarray Sum Equals K",
      platformName: "LeetCode",
      platformUrl: leetcode("subarray-sum-equals-k"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix Sum + Hash Map",
      rating: 10,
      shortNote: "Count previous prefix sums equal to current minus k.",
      longNote: "Each prefix sum stores how many times it has appeared so far.",
      tags: ["hashing", "prefix sum", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Continuous Subarray Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("continuous-subarray-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix Sum + Hash Map",
      rating: 8,
      shortNote: "Track first occurrence of each prefix modulo k.",
      longNote: "Matching remainders at distance > 1 indicate a subarray sum divisible by k.",
      tags: ["hashing", "prefix sum", "modulo"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Contiguous Array",
      platformName: "LeetCode",
      platformUrl: leetcode("contiguous-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Prefix Sum + Hash Map",
      rating: 9,
      shortNote: "Map 0 to -1 and track earliest prefix sum positions.",
      longNote: "Equal 0/1 counts translate into repeated transformed prefix sums.",
      tags: ["hashing", "prefix sum", "arrays"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Longest Consecutive Sequence",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-consecutive-sequence"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Set",
      rating: 10,
      shortNote: "Only start expanding from numbers that begin a sequence.",
      longNote: "Checking n-1 not present avoids re-walking every chain repeatedly.",
      tags: ["hashing", "hash set", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "4Sum II",
      platformName: "LeetCode",
      platformUrl: leetcode("4sum-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Store pair sums from first two arrays, query complements from the other two.",
      longNote: "Hashing all partial sums collapses O(n^4) brute force to O(n^2).",
      tags: ["hashing", "hash map", "arrays"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...hashingRoadmap("Advanced Hashing", 4, [
    {
      roadmapOrder: 1,
      title: "Group Anagrams",
      platformName: "LeetCode",
      platformUrl: leetcode("group-anagrams"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 10,
      shortNote: "Use sorted word or frequency signature as the map key.",
      longNote: "Equivalent anagrams collapse into the same canonical representation.",
      tags: ["hashing", "hash map", "strings"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Isomorphic Strings",
      platformName: "LeetCode",
      platformUrl: leetcode("isomorphic-strings"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Maintain both forward and reverse mappings.",
      longNote: "Two-way checks ensure a bijection between characters.",
      tags: ["hashing", "hash map", "strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Word Pattern",
      platformName: "LeetCode",
      platformUrl: leetcode("word-pattern"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 8,
      shortNote: "Match pattern chars and words with a bijective map.",
      longNote: "Both char->word and word->char structures keep the mapping valid.",
      tags: ["hashing", "hash map", "strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Find Duplicate File in System",
      platformName: "LeetCode",
      platformUrl: leetcode("find-duplicate-file-in-system"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map",
      rating: 7,
      shortNote: "Hash file contents to the list of file paths sharing them.",
      longNote: "Parse each directory string and group paths by identical content payloads.",
      tags: ["hashing", "hash map", "filesystem"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "LRU Cache",
      platformName: "LeetCode",
      platformUrl: leetcode("lru-cache"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Hash Map + Doubly Linked List",
      rating: 10,
      shortNote: "Map keys to DLL nodes and move recent nodes to the front.",
      longNote: "The map gives O(1) access, and the doubly linked list preserves recency order.",
      tags: ["hashing", "design", "linked list"],
      priority: 10,
      isPinned: true,
    },
  ]),
  ...twoPointersRoadmap("Basic Two Pointers", 1, [
    {
      roadmapOrder: 1,
      title: "Valid Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 9,
      shortNote: "Skip non-alphanumeric chars and compare inward from both ends.",
      longNote: "Normalize with two pointers and only stop when a valid mismatching pair appears.",
      tags: ["two pointers", "strings"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Reverse String",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 8,
      shortNote: "Swap characters from both ends until pointers meet.",
      longNote: "In-place reversal is the cleanest way to build intuition for left-right pointer movement.",
      tags: ["two pointers", "strings", "in-place"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Merge Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("merge-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Same Direction",
      rating: 9,
      shortNote: "Fill nums1 from the back using the largest remaining element.",
      longNote: "Starting from the end avoids overwriting useful values in the first array.",
      tags: ["two pointers", "arrays", "sorting"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Remove Duplicates from Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("remove-duplicates-from-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Same Direction",
      rating: 9,
      shortNote: "Keep a write index for the next unique value.",
      longNote: "One pointer reads the array and the other compacts distinct values in place.",
      tags: ["two pointers", "arrays", "in-place"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Squares of a Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("squares-of-a-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 8,
      shortNote: "Compare absolute values at both ends and place the larger square last.",
      longNote: "The largest square comes from an endpoint, so build the answer array from right to left.",
      tags: ["two pointers", "arrays"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...twoPointersRoadmap("Opposite Direction", 2, [
    {
      roadmapOrder: 1,
      title: "Two Sum II - Input Array Is Sorted",
      platformName: "LeetCode",
      platformUrl: leetcode("two-sum-ii-input-array-is-sorted"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 10,
      shortNote: "Move left or right pointer based on whether the sum is too small or large.",
      longNote: "Sorted order guarantees that shrinking or expanding the pair space is always meaningful.",
      tags: ["two pointers", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Container With Most Water",
      platformName: "LeetCode",
      platformUrl: leetcode("container-with-most-water"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 10,
      shortNote: "Always move the shorter wall to search for a taller boundary.",
      longNote: "The limiting height decides the area, so keeping the shorter side cannot improve the result.",
      tags: ["two pointers", "greedy", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "3Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("3sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sorting + Two Pointers",
      rating: 10,
      shortNote: "Fix one index, then solve the remaining pair with inward pointers.",
      longNote: "Sorting helps both duplicate skipping and the classic pair-sum sweep.",
      tags: ["two pointers", "sorting", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "4Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("4sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sorting + Two Pointers",
      rating: 9,
      shortNote: "Fix two positions, then finish with a sorted two-pointer sweep.",
      longNote: "The main challenge is duplicate handling plus pruning impossible ranges early.",
      tags: ["two pointers", "sorting", "arrays"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Boats to Save People",
      platformName: "LeetCode",
      platformUrl: leetcode("boats-to-save-people"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Greedy + Two Pointers",
      rating: 8,
      shortNote: "Try pairing the lightest and heaviest person after sorting.",
      longNote: "If the heaviest person cannot pair with the lightest, they cannot pair with anyone.",
      tags: ["two pointers", "greedy", "sorting"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...twoPointersRoadmap("Fast & Slow Pointers", 3, [
    {
      roadmapOrder: 1,
      title: "Linked List Cycle",
      platformName: "LeetCode",
      platformUrl: leetcode("linked-list-cycle"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Fast & Slow Pointer",
      rating: 10,
      shortNote: "A fast pointer eventually meets the slow pointer if a cycle exists.",
      longNote: "Floyd's algorithm gives O(1) extra space cycle detection for linked structures.",
      tags: ["two pointers", "linked list"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Linked List Cycle II",
      platformName: "LeetCode",
      platformUrl: leetcode("linked-list-cycle-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Fast & Slow Pointer",
      rating: 10,
      shortNote: "After the meeting point, reset one pointer to head to find cycle start.",
      longNote: "The distance relationship between head, entry, and meeting point makes the second walk converge at the cycle entry.",
      tags: ["two pointers", "linked list"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Middle of the Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("middle-of-the-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Fast & Slow Pointer",
      rating: 10,
      shortNote: "Slow moves one step while fast moves two.",
      longNote: "When the fast pointer reaches the end, the slow pointer sits at the middle.",
      tags: ["two pointers", "linked list"],
      priority: 10,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Happy Number",
      platformName: "LeetCode",
      platformUrl: leetcode("happy-number"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Fast & Slow Pointer",
      rating: 8,
      shortNote: "Treat the digit-square transform as a linked structure and detect cycles.",
      longNote: "This problem works nicely as a non-linked-list application of Floyd's cycle detection.",
      tags: ["two pointers", "math"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Find the Duplicate Number",
      platformName: "LeetCode",
      platformUrl: leetcode("find-the-duplicate-number"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Cycle Detection",
      rating: 10,
      shortNote: "Model values as next pointers and find the cycle entry.",
      longNote: "The duplicate creates a cycle in the implicit graph, which Floyd's algorithm can locate.",
      tags: ["two pointers", "arrays", "cycle detection"],
      priority: 10,
      isPinned: true,
    },
  ]),
  ...twoPointersRoadmap("Advanced Applications", 4, [
    {
      roadmapOrder: 1,
      title: "Sort Colors",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-colors"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Dutch National Flag",
      rating: 10,
      shortNote: "Partition 0s, 1s, and 2s with low, mid, and high pointers.",
      longNote: "Three-way partitioning sorts the array in one pass with constant extra space.",
      tags: ["two pointers", "arrays", "sorting"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Move Zeroes",
      platformName: "LeetCode",
      platformUrl: leetcode("move-zeroes"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Same Direction",
      rating: 10,
      shortNote: "Compact non-zero values first, then leave zeros behind.",
      longNote: "A write pointer keeps the stable order of non-zero elements while pushing zeros to the end.",
      tags: ["two pointers", "arrays", "in-place"],
      priority: 10,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Backspace String Compare",
      platformName: "LeetCode",
      platformUrl: leetcode("backspace-string-compare"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Backward Two Pointers",
      rating: 8,
      shortNote: "Walk from the end while counting pending backspaces.",
      longNote: "Backward scanning avoids rebuilding strings and naturally skips deleted characters.",
      tags: ["two pointers", "strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Interval List Intersections",
      platformName: "LeetCode",
      platformUrl: leetcode("interval-list-intersections"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Two Sorted Arrays",
      rating: 9,
      shortNote: "Compare current intervals and advance the one that ends first.",
      longNote: "Each pointer only moves forward, giving a linear merge-style traversal.",
      tags: ["two pointers", "intervals"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Trapping Rain Water",
      platformName: "LeetCode",
      platformUrl: leetcode("trapping-rain-water"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Opposite Direction",
      rating: 10,
      shortNote: "Track leftMax and rightMax while shrinking from both sides.",
      longNote: "Move the side with the smaller height because its water level is already determined.",
      tags: ["two pointers", "arrays"],
      priority: 10,
      isPinned: true,
    },
  ]),
  {
    title: "Valid Parentheses",
    topicSlug: "stack",
    platformName: "LeetCode",
    platformUrl: leetcode("valid-parentheses"),
    difficulty: "Easy",
    status: "solved",
    pattern: "Stack",
    rating: 8,
    shortNote: "Push opening brackets, pop on matching close.",
    longNote: "Classic stack usage. Handle mismatch and odd-length strings early.",
    tags: ["stack", "string"],
    priority: 8,
    isPinned: true,
  },
  {
    title: "Binary Tree Level Order Traversal",
    topicSlug: "trees",
    platformName: "LeetCode",
    platformUrl: leetcode("binary-tree-level-order-traversal"),
    difficulty: "Medium",
    status: "unsolved",
    pattern: "BFS",
    rating: 7,
    shortNote: "Use a queue and process level by level.",
    longNote: "Breadth-first traversal. Store nodes per level and append children in order.",
    tags: ["tree", "bfs"],
    priority: 7,
    isPinned: false,
  },
];
