import type { ProblemSeed, TopicSeed } from "./types.js";

export const topicSeeds3: TopicSeed[] = [
  {
    name: "Array",
    slug: "set3-array",
    order: 1,
    targetCount: 5,
    description: "Array Problems",
    accent: "#ef4444",
  },
  {
    name: "Sorting",
    slug: "set3-sorting",
    order: 2,
    targetCount: 5,
    description: "Sorting Problems",
    accent: "#22c55e",
  },
  {
    name: "Binary Search",
    slug: "set3-binary-search",
    order: 3,
    targetCount: 8,
    description: "Binary Search Problems",
    accent: "#f97316",
  },
  {
    name: "Two Pointers",
    slug: "set3-two-pointers",
    order: 4,
    targetCount: 4,
    description: "Two Pointers Problems",
    accent: "#84cc16",
  },
  {
    name: "Matrix",
    slug: "set3-matrix",
    order: 5,
    targetCount: 8,
    description: "Matrix Problems",
    accent: "#6366f1",
  },
  {
    name: "Strings",
    slug: "set3-strings",
    order: 6,
    targetCount: 13,
    description: "Strings Problems",
    accent: "#ef4444",
  },
  {
    name: "Recursion",
    slug: "set3-recursion",
    order: 7,
    targetCount: 13,
    description: "Recursion Problems",
    accent: "#a855f7",
  },
  {
    name: "Linked List",
    slug: "set3-linked-list",
    order: 8,
    targetCount: 16,
    description: "Linked List Problems",
    accent: "#0ea5e9",
  },
  {
    name: "Stack",
    slug: "set3-stack",
    order: 9,
    targetCount: 15,
    description: "Stack Problems",
    accent: "#0ea5e9",
  },
  {
    name: "Queue",
    slug: "set3-queue",
    order: 10,
    targetCount: 7,
    description: "Queue Problems",
    accent: "#22c55e",
  },
  {
    name: "Tree",
    slug: "set3-tree",
    order: 11,
    targetCount: 25,
    description: "Tree Problems",
    accent: "#6366f1",
  },
  {
    name: "BST",
    slug: "set3-bst",
    order: 12,
    targetCount: 17,
    description: "BST Problems",
    accent: "#10b981",
  },
  {
    name: "Heap",
    slug: "set3-heap",
    order: 13,
    targetCount: 14,
    description: "Heap Problems",
    accent: "#14b8a6",
  },
  {
    name: "Hashing",
    slug: "set3-hashing",
    order: 14,
    targetCount: 5,
    description: "Hashing Problems",
    accent: "#a855f7",
  },
  {
    name: "Graphs",
    slug: "set3-graphs",
    order: 15,
    targetCount: 29,
    description: "Graphs Problems",
    accent: "#a855f7",
  },
  {
    name: "Dynamic Programming",
    slug: "set3-dynamic-programming",
    order: 16,
    targetCount: 25,
    description: "Dynamic Programming Problems",
    accent: "#6366f1",
  },
  {
    name: "Trie",
    slug: "set3-trie",
    order: 17,
    targetCount: 3,
    description: "Trie Problems",
    accent: "#ec4899",
  },
  {
    name: "Segment Tree",
    slug: "set3-segment-tree",
    order: 18,
    targetCount: 1,
    description: "Segment Tree Problems",
    accent: "#22c55e",
  }
];

const leetcode = (slug: string) => `https://leetcode.com/problems/${slug}/`;
const gfg = (slug: string) => `https://www.geeksforgeeks.org/problems/${slug}/1`;

const roadmapForTopic = (
  topicSlug: string,
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
): ProblemSeed[] =>
  entries.map((entry) => ({
    ...entry,
    topicSlug,
    roadmapSection,
    roadmapSectionOrder,
  }));

const arrayRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-array", "Array", 1, entries);

const sortingRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-sorting", "Sorting", 2, entries);

const binarySearchRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-binary-search", "Binary Search", 3, entries);

const twoPointersRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-two-pointers", "Two Pointers", 4, entries);

const matrixRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-matrix", "Matrix", 5, entries);

const stringsRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-strings", "Strings", 6, entries);

const recursionRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-recursion", "Recursion", 7, entries);

const linkedListRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-linked-list", "Linked List", 8, entries);

const stackRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-stack", "Stack", 9, entries);

const queueRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-queue", "Queue", 10, entries);

const treeRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-tree", "Tree", 11, entries);

const bstRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-bst", "BST", 12, entries);

const heapRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-heap", "Heap", 13, entries);

const hashingRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-hashing", "Hashing", 14, entries);

const graphsRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-graphs", "Graphs", 15, entries);

const dynamicProgrammingRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-dynamic-programming", "Dynamic Programming", 16, entries);

const trieRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-trie", "Trie", 17, entries);

const segmentTreeRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set3-segment-tree", "Segment Tree", 18, entries);

export const problemSeeds3: ProblemSeed[] = [
  ...arrayRoadmap([
    {
      roadmapOrder: 1,
      title: "Reverse an Array",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("reverse-an-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["array"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Largest Element in an Array",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("largest-element-in-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["array"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Second Largest Element",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Second%20Largest%20Element",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["array"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Rotate Array",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["array"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Maximum Product Subarray",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-product-subarray"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["array"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...sortingRoadmap([
    {
      roadmapOrder: 1,
      title: "Selection Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("selection-sort"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["sorting"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Bubble Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("bubble-sort"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["sorting"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Insertion Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("insertion-sort"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["sorting"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Equilibrium Index",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Equilibrium%20Index",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["sorting"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Optimized Bubble Sort",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Optimized%20Bubble%20Sort",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["sorting"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...binarySearchRoadmap([
    {
      roadmapOrder: 1,
      title: "Find First and Last Position of Element in Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("find-first-and-last-position-of-element-in-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Search Insert Position",
      platformName: "LeetCode",
      platformUrl: leetcode("search-insert-position"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Peak Element",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("peak-element"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Ceil in a Sorted Array",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("ceil-in-a-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Search in Rotated Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("search-in-rotated-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Allocate Minimum Number of Pages",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("allocate-minimum-number-of-pages"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Search in Rotated Sorted Array II",
      platformName: "LeetCode",
      platformUrl: leetcode("search-in-rotated-sorted-array-ii"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Aggressive Cows",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("aggressive-cows"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["binary-search"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...twoPointersRoadmap([
    {
      roadmapOrder: 1,
      title: "Remove Duplicates from Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("remove-duplicates-from-sorted-array"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["two-pointers"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Subarray with Given Sum",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("subarray-with-given-sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["two-pointers"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Union of Two Sorted Arrays",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Union%20of%20Two%20Sorted%20Arrays",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["two-pointers"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Container With Most Water",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("container-with-most-water"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["two-pointers"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...matrixRoadmap([
    {
      roadmapOrder: 1,
      title: "Search a 2D Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("search-a-2d-matrix"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Sum of Matrix Elements",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Sum%20of%20Matrix%20Elements",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Set Matrix Zeroes",
      platformName: "LeetCode",
      platformUrl: leetcode("set-matrix-zeroes"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Transpose Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("transpose-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Rotate Image",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-image"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Search a 2D Matrix II",
      platformName: "LeetCode",
      platformUrl: leetcode("search-a-2d-matrix-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Diagonal Traverse",
      platformName: "LeetCode",
      platformUrl: leetcode("diagonal-traverse"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Count Zeros in a Sorted Matrix",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("count-zeros-in-a-sorted-matrix"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["matrix"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap([
    {
      roadmapOrder: 1,
      title: "Sort Characters By Frequency",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-characters-by-frequency"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Reverse String",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("reverse-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Valid Anagram",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-anagram"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Valid Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Minimum Deletions",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Minimum%20Deletions",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Merge Strings Alternately",
      platformName: "LeetCode",
      platformUrl: leetcode("merge-strings-alternately"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "To Lower Case",
      platformName: "LeetCode",
      platformUrl: leetcode("to-lower-case"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Add Strings",
      platformName: "LeetCode",
      platformUrl: leetcode("add-strings"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Longest Substring Without Repeating Characters",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-substring-without-repeating-characters"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Longest Common Prefix",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-common-prefix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Longest Palindromic Substring",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-palindromic-substring"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Check if Strings are Rotations",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Check%20if%20Strings%20are%20Rotations",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Minimum Add to Make Parentheses Valid",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-add-to-make-parentheses-valid"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["strings"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...recursionRoadmap([
    {
      roadmapOrder: 1,
      title: "Print N to 1",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Print%20N%20to%201",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Print 1 to N",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Print%201%20to%20N",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Fibonacci Number",
      platformName: "LeetCode",
      platformUrl: leetcode("fibonacci-number"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Climbing Stairs",
      platformName: "LeetCode",
      platformUrl: leetcode("climbing-stairs"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Merge Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("merge-sort"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Quick Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("quick-sort"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Tower of Hanoi",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("tower-of-hanoi"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Combination Sum",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("combination-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Express Number as Sum of Powers",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Express%20Number%20as%20Sum%20of%20Powers",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Palindrome Partitioning",
      platformName: "LeetCode",
      platformUrl: leetcode("palindrome-partitioning"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Combinations",
      platformName: "LeetCode",
      platformUrl: leetcode("combinations"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Permutations",
      platformName: "LeetCode",
      platformUrl: leetcode("permutations"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Letter Combinations of a Phone Number",
      platformName: "LeetCode",
      platformUrl: leetcode("letter-combinations-of-a-phone-number"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...linkedListRoadmap([
    {
      roadmapOrder: 1,
      title: "Convert Array to Linked List",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Convert%20Array%20to%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Reverse Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Delete Middle Node of a Linked List",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Delete%20Middle%20Node%20of%20a%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Sort Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Sort%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Linked List Cycle",
      platformName: "LeetCode",
      platformUrl: leetcode("linked-list-cycle"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Find Length of Loop",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-length-of-loop"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Delete Node in a Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("delete-node-in-a-linked-list"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Insert into Sorted Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Insert%20into%20Sorted%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Palindrome Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("palindrome-linked-list"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Detect Loop",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Detect%20Loop",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Remove Loop",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Remove%20Loop",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Rearrange Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Rearrange%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Circular Doubly Linked List",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Circular%20Doubly%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Delete in Doubly Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Delete%20in%20Doubly%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Copy List with Random Pointer",
      platformName: "LeetCode",
      platformUrl: leetcode("copy-list-with-random-pointer"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Reverse Linked List II",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-linked-list-ii"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...stackRoadmap([
    {
      roadmapOrder: 1,
      title: "Implement Stack",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Implement%20Stack",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Stack using Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Stack%20using%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Stack using Queues",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("stack-using-queue"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Delete Middle Element of Stack",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Delete%20Middle%20Element%20of%20Stack",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Parenthesis Checker",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("parenthesis-checker"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Min Stack",
      platformName: "LeetCode",
      platformUrl: leetcode("min-stack"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "String Manipulation",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("string-manipulation"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Make The Array Beautiful",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Make%20The%20Array%20Beautiful",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Next Greater Element",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("next-greater-element"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Nearest Smaller to Left",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Nearest%20Smaller%20to%20Left",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Remove K Digits",
      platformName: "LeetCode",
      platformUrl: leetcode("remove-k-digits"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Change Parentheses",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Change%20Parentheses",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Largest Rectangle in Histogram",
      platformName: "LeetCode",
      platformUrl: leetcode("largest-rectangle-in-histogram"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Maximal Rectangle",
      platformName: "LeetCode",
      platformUrl: leetcode("maximal-rectangle"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Celebrity Problem",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Celebrity%20Problem",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["stack"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...queueRoadmap([
    {
      roadmapOrder: 1,
      title: "Circular Queue",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Circular%20Queue",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Queue using Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Queue%20using%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Reverse Queue",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Reverse%20Queue",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Queue using Stacks",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("queue-using-stack"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Stack using Queues",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("stack-using-queue"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Reverse First K Elements of Queue",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("reverse-first-k-elements-of-queue"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Circular Tour",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("circular-tour"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["queue"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...treeRoadmap([
    {
      roadmapOrder: 1,
      title: "Binary Tree Traversals",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Binary%20Tree%20Traversals",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Create Binary Tree",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Create%20Binary%20Tree",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Inorder Traversal",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("inorder-traversal"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Preorder Traversal",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("preorder-traversal"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Size of Binary Tree",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("size-of-binary-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Count Leaf Nodes",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Count%20Leaf%20Nodes",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Height of Binary Tree",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("height-of-binary-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Identical Trees",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Identical%20Trees",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Diameter of Binary Tree",
      platformName: "LeetCode",
      platformUrl: leetcode("diameter-of-binary-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Balanced Binary Tree",
      platformName: "LeetCode",
      platformUrl: leetcode("balanced-binary-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Left View",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Left%20View",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Bottom View",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Bottom%20View",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Sum at Odd Levels",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Sum%20at%20Odd%20Levels",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Root to Leaf Path Sum",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("root-to-leaf-path-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Lowest Common Ancestor",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Lowest%20Common%20Ancestor",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Preorder Traversal (Iterative)",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("preorder-traversal-iterative"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 17,
      title: "Vertical Traversal",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Vertical%20Traversal",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 18,
      title: "Print Nodes at Distance K",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Print%20Nodes%20at%20Distance%20K",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 19,
      title: "Spiral Traversal",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Spiral%20Traversal",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 20,
      title: "Boundary Traversal",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Boundary%20Traversal",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 21,
      title: "Maximum Path Sum",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("maximum-path-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 22,
      title: "Burning Tree",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("burning-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 23,
      title: "Children Sum Property",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Children%20Sum%20Property",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 24,
      title: "Construct Tree from Inorder & Preorder",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Construct%20Tree%20from%20Inorder%20%26%20Preorder",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 25,
      title: "Binary Tree to BST",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("binary-tree-to-bst"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["tree"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...bstRoadmap([
    {
      roadmapOrder: 1,
      title: "Search in BST",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Search%20in%20BST",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Minimum Element in BST",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("minimum-element-in-bst"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Kth Largest in BST",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Kth%20Largest%20in%20BST",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Validate BST",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Validate%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "BST Traversals",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20BST%20Traversals",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Kth Smallest in BST",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Kth%20Smallest%20in%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Largest BST in Binary Tree",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Largest%20BST%20in%20Binary%20Tree",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Morris Traversal",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Morris%20Traversal",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Inorder Successor in BST",
      platformName: "LeetCode",
      platformUrl: leetcode("inorder-successor-in-bst"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Flatten BST",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Flatten%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Preorder to BST",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Preorder%20to%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Find Ceiling in BST",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Find%20Ceiling%20in%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Ceil in BST",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Ceil%20in%20BST",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Predecessor and Successor",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("predecessor-and-successor"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Recover Binary Search Tree",
      platformName: "LeetCode",
      platformUrl: leetcode("recover-binary-search-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Minimum Absolute Difference in BST",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-absolute-difference-in-bst"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 17,
      title: "Fix Two Swapped Nodes",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Fix%20Two%20Swapped%20Nodes",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["bst"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...heapRoadmap([
    {
      roadmapOrder: 1,
      title: "Delete Node in BST",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Delete%20Node%20in%20BST",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "AVL Tree",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20AVL%20Tree",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Heap Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("heap-sort"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Height of Heap",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("height-of-heap"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Maximum Profit",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("maximum-profit"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Minimum Cost of Ropes",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("minimum-cost-of-ropes"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Magician and Chocolates",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Magician%20and%20Chocolates",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "K Largest Elements",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20K%20Largest%20Elements",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Pair in STL",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Pair%20in%20STL",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Sort by Frequency",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Sort%20by%20Frequency",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Sort by Second Value",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Sort%20by%20Second%20Value",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Merge K Sorted Arrays",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("merge-k-sorted-arrays"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Huffman Coding",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Huffman%20Coding",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Find Median from Data Stream",
      platformName: "LeetCode",
      platformUrl: leetcode("find-median-from-data-stream"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["heap"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...hashingRoadmap([
    {
      roadmapOrder: 1,
      title: "Hash Map Basics",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Hash%20Map%20Basics",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["hashing"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Smallest Range in K Lists",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Smallest%20Range%20in%20K%20Lists",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["hashing"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "3Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("3sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["hashing"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Longest Subarray with Equal 0s and 1s",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Longest%20Subarray%20with%20Equal%200s%20and%201s",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["hashing"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Count Distinct Elements in Every Window",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("count-distinct-elements-in-every-window"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["hashing"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...graphsRoadmap([
    {
      roadmapOrder: 1,
      title: "BFS",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20BFS",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "DFS",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20DFS",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Shortest Path in Binary Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("shortest-path-in-binary-matrix"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Find Center of Star Graph",
      platformName: "LeetCode",
      platformUrl: leetcode("find-center-of-star-graph"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Number of Provinces",
      platformName: "LeetCode",
      platformUrl: leetcode("number-of-provinces"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Number of Islands",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("number-of-islands"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Detect Cycle in Undirected Graph",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Detect%20Cycle%20in%20Undirected%20Graph",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Rotten Oranges",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("rotten-oranges"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "01 Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("01-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Steps by Knight",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("steps-by-knight"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Replace O's with X's",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Replace%20O's%20with%20X's",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Surrounded Regions",
      platformName: "LeetCode",
      platformUrl: leetcode("surrounded-regions"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Detect Cycle in Directed Graph",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Detect%20Cycle%20in%20Directed%20Graph",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Topological Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("topological-sort"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Kahn's Algorithm",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Kahn's%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Dijkstra's Algorithm",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Dijkstra's%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 17,
      title: "Minimum Spanning Tree",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("minimum-spanning-tree"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 18,
      title: "Prim's Algorithm",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Prim's%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 19,
      title: "Kruskal's Algorithm",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Kruskal's%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 20,
      title: "Strongly Connected Components",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Strongly%20Connected%20Components",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 21,
      title: "Kosaraju's Algorithm",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Kosaraju's%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 22,
      title: "Bellman-Ford Algorithm",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Bellman-Ford%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 23,
      title: "Floyd-Warshall Algorithm",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Floyd-Warshall%20Algorithm",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 24,
      title: "Euler Circuit",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Euler%20Circuit",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 25,
      title: "Cycle in Directed Graph",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Cycle%20in%20Directed%20Graph",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 26,
      title: "Alien Dictionary",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("alien-dictionary"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 27,
      title: "Critical Connections",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("critical-connections"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 28,
      title: "Articulation Point",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Articulation%20Point",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 29,
      title: "Articulation Points",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Articulation%20Points",
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["graphs"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...dynamicProgrammingRoadmap([
    {
      roadmapOrder: 1,
      title: "Climbing Stairs",
      platformName: "LeetCode",
      platformUrl: leetcode("climbing-stairs"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "House Robber II",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("house-robber-ii"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "House Robber",
      platformName: "LeetCode",
      platformUrl: leetcode("house-robber"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Coin Change II",
      platformName: "LeetCode",
      platformUrl: leetcode("coin-change-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Decode Ways",
      platformName: "LeetCode",
      platformUrl: leetcode("decode-ways"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Fractional Knapsack",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("fractional-knapsack"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "0/1 Knapsack",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%200%2F1%20Knapsack",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Longest Common Subsequence",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("longest-common-subsequence"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Longest Palindromic Subsequence",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-palindromic-subsequence"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Longest Repeating Subsequence",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("longest-repeating-subsequence"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Minimum Edit Distance",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Minimum%20Edit%20Distance",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Longest Increasing Subsequence",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("longest-increasing-subsequence"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Unique Paths",
      platformName: "LeetCode",
      platformUrl: leetcode("unique-paths"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Unique Paths II",
      platformName: "LeetCode",
      platformUrl: leetcode("unique-paths-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Minimum Path Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("minimum-path-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Best Time to Buy and Sell Stock",
      platformName: "LeetCode",
      platformUrl: leetcode("best-time-to-buy-and-sell-stock"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 17,
      title: "Best Time to Buy and Sell Stock II",
      platformName: "LeetCode",
      platformUrl: leetcode("best-time-to-buy-and-sell-stock-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 18,
      title: "Subset Sum Problem",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("subset-sum-problem"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 19,
      title: "Space Optimization in DP",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Space%20Optimization%20in%20DP",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 20,
      title: "Paint House III",
      platformName: "LeetCode",
      platformUrl: leetcode("paint-house-iii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 21,
      title: "Best Time to Buy and Sell Stock IV",
      platformName: "LeetCode",
      platformUrl: leetcode("best-time-to-buy-and-sell-stock-iv"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 22,
      title: "Maximum Score from Performing Multiplication Operations",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-score-from-performing-multiplication-operations"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 23,
      title: "Egg Dropping Puzzle",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("egg-dropping-puzzle"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 24,
      title: "Longest Increasing Path in a Matrix",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("longest-increasing-path-in-a-matrix"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 25,
      title: "Word Break",
      platformName: "LeetCode",
      platformUrl: leetcode("word-break"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["dynamic-programming"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...trieRoadmap([
    {
      roadmapOrder: 1,
      title: "Implement Trie",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Implement%20Trie",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["trie"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Trie (Insert, Search, StartsWith)",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Trie%20(Insert%2C%20Search%2C%20StartsWith)",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["trie"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Phone Directory",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("phone-directory"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["trie"],
      priority: 5,
      isPinned: false,
    },
  ]),
  ...segmentTreeRoadmap([
    {
      roadmapOrder: 1,
      title: "Range Sum Query",
      platformName: "LeetCode",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Range%20Sum%20Query",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "General",
      rating: 5,
      shortNote: "",
      longNote: "",
      tags: ["segment-tree"],
      priority: 5,
      isPinned: false,
    },
  ]),

];
