import type { ProblemSeed, TopicSeed } from "./types.js";

export const topicSeeds2: TopicSeed[] = [
  {
    name: "Binary Search",
    slug: "set2-binary-search",
    order: 1,
    targetCount: 10,
    description: "Binary search on arrays, answer space, and monotonic conditions.",
    accent: "#93c5fd",
  },
  {
    name: "Two Pointers",
    slug: "set2-two-pointers",
    order: 2,
    targetCount: 7,
    description: "Left-right scanning, pair matching, and range optimization.",
    accent: "#fdba74",
  },
  {
    name: "2D Array",
    slug: "set2-2d-array",
    order: 3,
    targetCount: 15,
    description: "Matrix traversal, transformation, and search.",
    accent: "#fda4af",
  },
  {
    name: "Strings",
    slug: "set2-strings",
    order: 4,
    targetCount: 16,
    description: "String manipulation, parsing, frequency tricks, and pattern matching.",
    accent: "#86efac",
  },
  {
    name: "Recursion",
    slug: "set2-recursion",
    order: 5,
    targetCount: 33,
    description: "Core recursion concepts, backtracking, and combination generation.",
    accent: "#fcd34d",
  },
  {
    name: "Linked List",
    slug: "set2-linked-list",
    order: 6,
    targetCount: 9,
    description: "Single linked list patterns, reversals, and cycle logic.",
    accent: "#67e8f9",
  },
  {
    name: "Doubly Linked List",
    slug: "set2-doubly-linked-list",
    order: 7,
    targetCount: 8,
    description: "Doubly linked list manipulations and advanced patterns.",
    accent: "#c4b5fd",
  },
  {
    name: "Circular Linked List",
    slug: "set2-circular-linked-list",
    order: 8,
    targetCount: 10,
    description: "Circular linked list specific problems and cycles.",
    accent: "#f9a8d4",
  },
  {
    name: "Stack",
    slug: "set2-stack",
    order: 9,
    targetCount: 21,
    description: "Stack usage, parsing, and expression logic.",
    accent: "#fca5a5",
  },
  {
    name: "Queue",
    slug: "set2-queue",
    order: 10,
    targetCount: 7,
    description: "Queue data structure and algorithms.",
    accent: "#f59e0b",
  },
  {
    name: "Tree",
    slug: "set2-tree",
    order: 11,
    targetCount: 23,
    description: "Binary Trees traversals and properties.",
    accent: "#10b981",
  },
  {
    name: "Binary Search Tree",
    slug: "set2-bst",
    order: 12,
    targetCount: 15,
    description: "Binary Search Tree operations and properties.",
    accent: "#059669",
  },
  {
    name: "Heap",
    slug: "set2-heap",
    order: 13,
    targetCount: 8,
    description: "Priority queues and Heap algorithms.",
    accent: "#6366f1",
  },
];

const leetcode = (slug: string) => `https://leetcode.com/problems/${slug}/`;
const gfg = (slug: string) => `https://www.geeksforgeeks.org/problems/${slug}/1`;

const roadmapForTopic = (
  topicSlug: string,
  roadmapSection: string,
  roadmapSectionOrder: number,
  entries: Array<
    Omit<ProblemSeed, "topicSlug"> & {
      roadmapOrder: number;
    }
  >
): ProblemSeed[] =>
  entries.map((entry) => ({
    ...entry,
    topicSlug,
    roadmapSection,
    roadmapSectionOrder,
  }));

const binarySearchRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-binary-search", "Binary Search Patterns", 1, entries);

const twoPointersRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-two-pointers", "Two Pointers Patterns", 2, entries);

const twoDArrayRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-2d-array", "2D Array & Matrix", 3, entries);

const stringsRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-strings", "String Manipulation & Matching", 4, entries);

const recursionRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-recursion", "Recursion & Backtracking", 5, entries);

const linkedListRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-linked-list", "Linked List", 6, entries);

const doublyLinkedListRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-doubly-linked-list", "Doubly Linked List", 7, entries);

const circularLinkedListRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-circular-linked-list", "Circular Linked List", 8, entries);

const stackRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-stack", "Stack", 9, entries);

const queueRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-queue", "Queue", 10, entries);

const treeRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-tree", "Tree", 11, entries);

const bstRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-bst", "Binary Search Tree", 12, entries);

const heapRoadmap = (entries: Array<Omit<ProblemSeed, "topicSlug"> & { roadmapOrder: number; }>) => 
  roadmapForTopic("set2-heap", "Heap", 13, entries);

export const problemSeeds2: ProblemSeed[] = [
  ...binarySearchRoadmap([
    {
      roadmapOrder: 1,
      title: "Find First and Last Position of Element in Sorted Array (Left Most & Right Most)",
      platformName: "LeetCode",
      platformUrl: leetcode("find-first-and-last-position-of-element-in-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 9,
      shortNote: "Find the starting and ending position of a given target value.",
      longNote: "Use binary search twice: once to find the first occurrence (lower bound) and once to find the last occurrence (upper bound).",
      tags: ["binary-search", "arrays"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Sqrt(x)",
      platformName: "LeetCode",
      platformUrl: leetcode("sqrtx"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Compute and return the square root of x.",
      longNote: "Binary search on the answer space [0, x]. If mid * mid <= x, it's a potential answer, move left pointer.",
      tags: ["binary-search", "math"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Peak Index in a Mountain Array",
      platformName: "LeetCode",
      platformUrl: leetcode("peak-index-in-a-mountain-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Find the peak element in a mountain array.",
      longNote: "If arr[mid] < arr[mid + 1], the peak is to the right. Otherwise, the peak is to the left or at mid.",
      tags: ["binary-search", "arrays"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Find Minimum in Rotated Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("find-minimum-in-rotated-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 9,
      shortNote: "Find the minimum element in an array that has been rotated.",
      longNote: "Compare mid with high. If arr[mid] > arr[high], min is in the right half. Else, it's in the left half (including mid).",
      tags: ["binary-search", "arrays"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "Search in Rotated Sorted Array",
      platformName: "LeetCode",
      platformUrl: leetcode("search-in-rotated-sorted-array"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 10,
      shortNote: "Search for a target value in a rotated sorted array.",
      longNote: "Determine which half is properly sorted. If the target falls in the sorted half's range, search there. Otherwise, search the other half.",
      tags: ["binary-search", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 6,
      title: "Find Nth Root Of M",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-nth-root-of-m5843"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search on Answer",
      rating: 8,
      shortNote: "Find the Nth root of an integer M.",
      longNote: "Binary search from 1 to M. Calculate mid^N. If it equals M, return mid. Avoid overflow by breaking early if power exceeds M.",
      tags: ["binary-search", "math"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Allocate Minimum Number of Pages",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("allocate-minimum-number-of-pages0937"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Binary Search on Answer",
      rating: 10,
      shortNote: "Allocate books such that max pages assigned to a student is minimized.",
      longNote: "Search space is [max(pages), sum(pages)]. Use a helper function to check if a max_page limit is valid for M students.",
      tags: ["binary-search", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "Capacity To Ship Packages Within D Days",
      platformName: "LeetCode",
      platformUrl: leetcode("capacity-to-ship-packages-within-d-days"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search on Answer",
      rating: 9,
      shortNote: "Find min capacity to ship all packages within D days.",
      longNote: "Similar to Book Allocation. Search space [max(weights), sum(weights)]. Helper function checks if days required <= D.",
      tags: ["binary-search", "arrays"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Aggressive Cows",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("aggressive-cows"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Binary Search on Answer",
      rating: 10,
      shortNote: "Place cows such that minimum distance between them is maximized.",
      longNote: "Sort array. Search space is [1, max-min]. Helper function checks if C cows can be placed with at least 'mid' distance between them.",
      tags: ["binary-search", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 10,
      title: "Koko Eating Bananas",
      platformName: "LeetCode",
      platformUrl: leetcode("koko-eating-bananas"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search on Answer",
      rating: 9,
      shortNote: "Find minimum eating speed to eat all bananas within H hours.",
      longNote: "Search space [1, max(piles)]. Helper function calculates total hours to eat all piles at speed 'mid' and checks if <= H.",
      tags: ["binary-search", "arrays"],
      priority: 9,
      isPinned: false,
    },
  ]),
  ...twoPointersRoadmap([
    {
      roadmapOrder: 1,
      title: "Segregate 0s and 1s",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("segregate-0s-and-1s5106"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 7,
      shortNote: "Segregate an array of 0s and 1s.",
      longNote: "Use left and right pointers. If left is 1 and right is 0, swap them and move both pointers inward.",
      tags: ["two-pointers", "arrays"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Two Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("two-sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing / Two Pointers",
      rating: 10,
      shortNote: "Find two numbers that add up to a target.",
      longNote: "Can be solved with Two Pointers if sorted, but usually solved with Hash Map for O(N) time.",
      tags: ["two-pointers", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Find Pair Given Difference",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-pair-given-difference1559"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 8,
      shortNote: "Find if there exists a pair with a given difference.",
      longNote: "Sort the array. Use two pointers i=0, j=1. If arr[j]-arr[i] == diff, found. If < diff, j++. If > diff, i++.",
      tags: ["two-pointers", "arrays"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Prefix and Suffix Sum (Equilibrium Point)",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("equilibrium-point-1587115620"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Prefix Sum",
      rating: 8,
      shortNote: "Find element where left sum equals right sum.",
      longNote: "Calculate total sum. Iterate, keeping a running left sum, and check if leftSum == totalSum - leftSum - arr[i].",
      tags: ["prefix-sum", "arrays"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Maximum Subarray (Kadane's Algorithm)",
      platformName: "LeetCode",
      platformUrl: leetcode("maximum-subarray"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Kadane's",
      rating: 10,
      shortNote: "Find contiguous subarray with the largest sum.",
      longNote: "Keep a running sum. If it becomes negative, reset it to 0. Update max_sum at each step.",
      tags: ["arrays", "dynamic-programming"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 6,
      title: "Trapping Rain Water",
      platformName: "LeetCode",
      platformUrl: leetcode("trapping-rain-water"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 10,
      shortNote: "Calculate how much water it can trap after raining.",
      longNote: "Use left and right pointers with left_max and right_max. Move the pointer pointing to the smaller max and compute water.",
      tags: ["two-pointers", "arrays"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 7,
      title: "3Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("3sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 10,
      shortNote: "Find all unique triplets that sum to zero.",
      longNote: "Sort the array. Iterate i, and use two pointers (left, right) for the remaining array. Skip duplicates to avoid duplicate triplets.",
      tags: ["two-pointers", "arrays"],
      priority: 10,
      isPinned: true,
    },
  ]),
  ...twoDArrayRoadmap([
    {
      roadmapOrder: 1,
      title: "Search a 2D Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("search-a-2d-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 9,
      shortNote: "Search for a value in an m x n matrix.",
      longNote: "Treat the 2D matrix as a 1D sorted array and perform binary search.",
      tags: ["2d-array", "binary-search"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 2,
      title: "Addition of two square matrices",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("addition-of-two-square-matrices4916"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 6,
      shortNote: "Add two matrices.",
      longNote: "Iterate through rows and columns and add corresponding elements.",
      tags: ["2d-array"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Row with max 1s",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("row-with-max-1s0023"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Traversal / Binary Search",
      rating: 8,
      shortNote: "Find the row with the maximum number of 1s in a boolean matrix.",
      longNote: "Start from top-right. If 1, move left and update max row. If 0, move down.",
      tags: ["2d-array", "binary-search"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Matrix Diagonal Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("matrix-diagonal-sum"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 7,
      shortNote: "Calculate sum of primary and secondary diagonals.",
      longNote: "Iterate i from 0 to n. Add mat[i][i] and mat[i][n-1-i]. If n is odd, subtract the middle element to avoid double counting.",
      tags: ["2d-array", "math"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Reverse each row in a matrix",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/reverse-each-row-in-a-matrix-1587115621/1",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 7,
      shortNote: "Reverse the elements in each row of a matrix.",
      longNote: "Use two pointers for each row to reverse it in-place.",
      tags: ["2d-array", "two-pointers"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Print Matrix in snake pattern",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("print-matrix-in-snake-pattern-1587115621"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 7,
      shortNote: "Print matrix elements in a snake-like sequence.",
      longNote: "Iterate rows. If row index is even, traverse left to right. If odd, traverse right to left.",
      tags: ["2d-array"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Spiral Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("spiral-matrix"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Spiral Traversal",
      rating: 10,
      shortNote: "Return all elements in spiral order.",
      longNote: "Use 4 boundaries (top, bottom, left, right). Traverse each boundary and adjust them inwards.",
      tags: ["2d-array"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "Transpose Matrix",
      platformName: "LeetCode",
      platformUrl: leetcode("transpose-matrix"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Matrix Math",
      rating: 8,
      shortNote: "Return the transpose of a 2D matrix.",
      longNote: "Swap mat[i][j] with mat[j][i]. For non-square matrices, create a new n x m matrix.",
      tags: ["2d-array"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Rotate Image",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-image"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Matrix Math",
      rating: 10,
      shortNote: "Rotate a 2D matrix by 90 degrees clockwise.",
      longNote: "First transpose the matrix (swap mat[i][j] with mat[j][i]), then reverse each row.",
      tags: ["2d-array", "math"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 10,
      title: "Rotate matrix elements clockwise by K",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.geeksforgeeks.org/problems/rotate-matrix-elements-clockwise-1587115621/1",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Matrix Math",
      rating: 8,
      shortNote: "Shift elements in matrix rings by K positions.",
      longNote: "Extract rings into 1D arrays, rotate them by K, and place them back.",
      tags: ["2d-array"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Search a 2D Matrix II",
      platformName: "LeetCode",
      platformUrl: leetcode("search-a-2d-matrix-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search Tree logic",
      rating: 10,
      shortNote: "Search in a matrix sorted row-wise and column-wise.",
      longNote: "Start at top-right corner. If target < current, move left. If target > current, move down.",
      tags: ["2d-array", "binary-search"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 12,
      title: "Search in a sorted Matrix",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("search-in-a-matrix-1587115621"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Binary Search",
      rating: 8,
      shortNote: "Similar to Search a 2D Matrix II.",
      longNote: "Use the top-right corner approach.",
      tags: ["2d-array", "binary-search"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Set Matrix Zeroes",
      platformName: "LeetCode",
      platformUrl: leetcode("set-matrix-zeroes"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "In-place Hashing",
      rating: 10,
      shortNote: "If an element is 0, set its entire row and column to 0.",
      longNote: "Use the first row and first column as markers. Handle the first row/col separately with boolean flags.",
      tags: ["2d-array", "hashing"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 14,
      title: "Find Missing And Repeating",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-missing-and-repeating2512"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Math / XOR",
      rating: 9,
      shortNote: "Find the missing and repeating number in an array.",
      longNote: "Can use Math (sum of n, sum of squares) or XOR. Modifying the array by negating values at indices is also possible.",
      tags: ["arrays", "math"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Majority Element",
      platformName: "LeetCode",
      platformUrl: leetcode("majority-element"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Moore's Voting Algorithm",
      rating: 9,
      shortNote: "Find the element that appears more than n/2 times.",
      longNote: "Use Moore's Voting Algorithm: maintain a count and candidate. If count is 0, update candidate. If current == candidate, count++, else count--.",
      tags: ["arrays"],
      priority: 9,
      isPinned: false,
    },
  ]),
  ...stringsRoadmap([
    {
      roadmapOrder: 1,
      title: "Defanging an IP Address",
      platformName: "LeetCode",
      platformUrl: leetcode("defanging-an-ip-address"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "String Manipulation",
      rating: 6,
      shortNote: "Replace every period '.' with '[.]'.",
      longNote: "Iterate over the string and append to a new string, replacing '.' as needed.",
      tags: ["strings"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Rotate String (Check if string is a rotation)",
      platformName: "LeetCode",
      platformUrl: leetcode("rotate-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "String Matching",
      rating: 8,
      shortNote: "Check if one string is a rotation of another.",
      longNote: "Concatenate the first string with itself (s + s). The second string must be a substring of this concatenated string.",
      tags: ["strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Valid Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 9,
      shortNote: "Check if string is palindrome ignoring non-alphanumeric characters.",
      longNote: "Use two pointers, left and right. Skip non-alphanumeric characters and compare the rest.",
      tags: ["strings", "two-pointers"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Sort a String",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("sort-a-string2943"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Counting Sort",
      rating: 7,
      shortNote: "Sort a string of characters.",
      longNote: "Use counting sort (frequency array of size 26) to sort the string in O(N) time.",
      tags: ["strings", "sorting"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Longest Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-palindrome"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing / Counting",
      rating: 8,
      shortNote: "Length of the longest palindrome that can be built.",
      longNote: "Count frequencies. Add even frequencies. For odd frequencies, add (count - 1). If there is any odd frequency, add 1 for the center.",
      tags: ["strings", "hashing"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Reverse Words in a String",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-words-in-a-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "String Manipulation",
      rating: 9,
      shortNote: "Reverse the order of words in a string.",
      longNote: "Split by spaces, filter empty strings, reverse the array of words, and join with a space.",
      tags: ["strings", "two-pointers"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 7,
      title: "Sort Vowels in a String",
      platformName: "LeetCode",
      platformUrl: leetcode("sort-vowels-in-a-string"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "String Manipulation",
      rating: 8,
      shortNote: "Sort only the vowels in a string while keeping consonants in place.",
      longNote: "Extract all vowels, sort them, and iterate the original string to replace vowels with the sorted ones.",
      tags: ["strings", "sorting"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Add Strings",
      platformName: "LeetCode",
      platformUrl: leetcode("add-strings"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Math / Simulation",
      rating: 8,
      shortNote: "Add two non-negative numbers represented as strings.",
      longNote: "Iterate from right to left, maintaining a carry, just like manual addition.",
      tags: ["strings", "math"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Roman to Integer",
      platformName: "LeetCode",
      platformUrl: leetcode("roman-to-integer"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Hashing",
      rating: 9,
      shortNote: "Convert a Roman numeral to an integer.",
      longNote: "If a smaller numeral appears before a larger one, subtract it. Otherwise, add it.",
      tags: ["strings", "hashing"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Factorials of large numbers",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("factorials-of-large-numbers2508"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Math / Simulation",
      rating: 9,
      shortNote: "Find the factorial of a large number as a string.",
      longNote: "Use an array to store digits. Multiply the array by numbers from 2 to N, carrying over digits > 9.",
      tags: ["strings", "math"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Longest Substring Without Repeating Characters",
      platformName: "LeetCode",
      platformUrl: leetcode("longest-substring-without-repeating-characters"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Find the length of the longest substring without repeating characters.",
      longNote: "Use a sliding window with a hash set or array to track character indices.",
      tags: ["strings", "sliding-window"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 12,
      title: "Smallest window in a string containing all the characters of another string",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Sliding Window",
      rating: 10,
      shortNote: "Find the smallest window containing all characters of a pattern.",
      longNote: "Use two pointers. Expand the window until all pattern characters are found, then shrink it from the left to minimize.",
      tags: ["strings", "sliding-window"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 13,
      title: "Longest Prefix Suffix (LPS Array)",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("longest-prefix-suffix2527"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "KMP Algorithm",
      rating: 10,
      shortNote: "Find the length of the longest proper prefix which is also a suffix.",
      longNote: "Compute the LPS array used in the KMP string matching algorithm.",
      tags: ["strings", "pattern-matching"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 14,
      title: "Find the Index of the First Occurrence in a String (String Matching)",
      platformName: "LeetCode",
      platformUrl: leetcode("find-the-index-of-the-first-occurrence-in-a-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "KMP / Rabin Karp",
      rating: 9,
      shortNote: "Implement strStr().",
      longNote: "Can be solved naively, but optimized using KMP or Rabin-Karp algorithms.",
      tags: ["strings", "pattern-matching"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Palindrome & Circular Match",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Palindrome%20%26%20Circular%20Match",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "String Manipulation",
      rating: 7,
      shortNote: "Check circular palindromes or advanced matching.",
      longNote: "Depending on the exact problem, usually involves string concatenation (s+s) to simulate circular properties.",
      tags: ["strings"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Repeated String Match",
      platformName: "LeetCode",
      platformUrl: leetcode("repeated-string-match"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "String Matching",
      rating: 8,
      shortNote: "Min number of times A has to be repeated such that B is a substring of it.",
      longNote: "Repeat A until its length is >= B's length. Check if B is a substring. If not, repeat A one more time and check again.",
      tags: ["strings", "pattern-matching"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...recursionRoadmap([
    {
      roadmapOrder: 1,
      title: "Print 1 To N Without Loop",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("print-1-to-n-without-using-loops-1587115620"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Basic Recursion",
      rating: 5,
      shortNote: "Print numbers from 1 to N recursively.",
      longNote: "Base case: if N==0 return. Recursive call for N-1, then print N.",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Print N to 1 without loop",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("print-n-to-1-without-loop"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Basic Recursion",
      rating: 5,
      shortNote: "Print numbers from N to 1 recursively.",
      longNote: "Print N, then recursive call for N-1. Base case if N==0 return.",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Factorial of N numbers",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-all-factorial-numbers-less-than-or-equal-to-n3548"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Basic Recursion",
      rating: 6,
      shortNote: "Find factorial recursively.",
      longNote: "Return N * factorial(N-1). Base case N=1 return 1.",
      tags: ["recursion"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Sum of first n terms",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("sum-of-first-n-terms5843"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Basic Recursion",
      rating: 5,
      shortNote: "Find sum of first N natural numbers recursively.",
      longNote: "Return N + sum(N-1). Base case N=1 return 1.",
      tags: ["recursion"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Power of Two",
      platformName: "LeetCode",
      platformUrl: leetcode("power-of-two"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Recursion / Math",
      rating: 7,
      shortNote: "Check if a number is a power of 2.",
      longNote: "Return (n>0) && (n & (n-1)) == 0. Or recursively check if n%2==0 and isPowerOfTwo(n/2).",
      tags: ["recursion", "math"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Sum of Squares",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("sum-of-squares-of-first-n-natural-numbers"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Basic Recursion",
      rating: 5,
      shortNote: "Find sum of squares of first N numbers.",
      longNote: "Return N*N + sum(N-1).",
      tags: ["recursion", "math"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Fibonacci Number",
      platformName: "LeetCode",
      platformUrl: leetcode("fibonacci-number"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Recursion / DP",
      rating: 8,
      shortNote: "Return the Nth Fibonacci number.",
      longNote: "Return F(N-1) + F(N-2). Base cases F(0)=0, F(1)=1. Use memoization to avoid O(2^N) time.",
      tags: ["recursion", "dynamic-programming"],
      priority: 8,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "Climbing Stairs (Nth Stair)",
      platformName: "LeetCode",
      platformUrl: leetcode("climbing-stairs"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Recursion / DP",
      rating: 9,
      shortNote: "Count distinct ways to climb N stairs (1 or 2 steps).",
      longNote: "Same recurrence as Fibonacci: Ways(N) = Ways(N-1) + Ways(N-2).",
      tags: ["recursion", "dynamic-programming"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 9,
      title: "Find GCD of two numbers",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("gcd-of-two-numbers3459"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Euclidean Algorithm",
      rating: 7,
      shortNote: "Find GCD recursively.",
      longNote: "return b == 0 ? a : gcd(b, a % b);",
      tags: ["recursion", "math"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Sum of Array",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("sum-of-array-elements2502"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Array Recursion",
      rating: 4,
      shortNote: "Find sum of array elements recursively.",
      longNote: "Return arr[n-1] + sum(arr, n-1).",
      tags: ["recursion", "arrays"],
      priority: 4,
      isPinned: false,
    },
    {
      roadmapOrder: 11,
      title: "Minimum Element in Array",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Minimum%20Element%20in%20Array",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Array Recursion",
      rating: 4,
      shortNote: "Find minimum element in an array recursively.",
      longNote: "Return min(arr[n-1], minRec(arr, n-1)).",
      tags: ["recursion", "arrays"],
      priority: 4,
      isPinned: false,
    },
    {
      roadmapOrder: 12,
      title: "Valid Palindrome",
      platformName: "LeetCode",
      platformUrl: leetcode("valid-palindrome"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers / Recursion",
      rating: 8,
      shortNote: "Check if a string is palindrome using recursion.",
      longNote: "Pass left and right pointers in recursive calls: isPal(s, l+1, r-1).",
      tags: ["recursion", "strings"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 13,
      title: "Count Vowels in a String",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Count%20Vowels%20in%20a%20String",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "String Recursion",
      rating: 4,
      shortNote: "Count vowels recursively.",
      longNote: "Check if s[n-1] is vowel + countRec(s, n-1).",
      tags: ["recursion", "strings"],
      priority: 4,
      isPinned: false,
    },
    {
      roadmapOrder: 14,
      title: "Reverse String",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-string"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers / Recursion",
      rating: 7,
      shortNote: "Reverse an array of characters recursively.",
      longNote: "Swap elements at left and right pointers, then recurse with l+1, r-1.",
      tags: ["recursion", "strings"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 15,
      title: "Lowercase to Uppercase",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("lower-case-to-upper-case3410"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "String Recursion",
      rating: 3,
      shortNote: "Convert lowercase string to uppercase recursively.",
      longNote: "Convert current char, then recurse for the rest.",
      tags: ["recursion", "strings"],
      priority: 3,
      isPinned: false,
    },
    {
      roadmapOrder: 16,
      title: "Linear Search",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Linear%20Search",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Array Recursion",
      rating: 4,
      shortNote: "Implement linear search recursively.",
      longNote: "If arr[n-1] == key return index, else recurse for n-1.",
      tags: ["recursion", "arrays"],
      priority: 4,
      isPinned: false,
    },
    {
      roadmapOrder: 17,
      title: "Binary Search (Recursive)",
      platformName: "LeetCode",
      platformUrl: leetcode("binary-search"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Divide and Conquer",
      rating: 8,
      shortNote: "Implement binary search using recursion.",
      longNote: "search(arr, low, high, target) -> search(arr, low, mid-1) or search(arr, mid+1, high).",
      tags: ["recursion", "binary-search"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 18,
      title: "Merge Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("merge-sort"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Divide and Conquer",
      rating: 10,
      shortNote: "Implement Merge Sort recursively.",
      longNote: "Split array in half, sort both halves recursively, then merge them.",
      tags: ["recursion", "sorting"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 19,
      title: "Quick Sort",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("quick-sort"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Divide and Conquer",
      rating: 10,
      shortNote: "Implement Quick Sort recursively.",
      longNote: "Pick a pivot, partition array around pivot, then recursively sort left and right partitions.",
      tags: ["recursion", "sorting"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 20,
      title: "Subsets (Subsequences)",
      platformName: "LeetCode",
      platformUrl: leetcode("subsets"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking / Pick-NotPick",
      rating: 10,
      shortNote: "Generate all possible subsets.",
      longNote: "For each element, either pick it or don't pick it. Base case: index == length.",
      tags: ["recursion", "backtracking"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 21,
      title: "Generate Parentheses",
      platformName: "LeetCode",
      platformUrl: leetcode("generate-parentheses"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking",
      rating: 10,
      shortNote: "Generate all combinations of well-formed parentheses.",
      longNote: "Recursively add '(' if open < n, and ')' if close < open.",
      tags: ["recursion", "backtracking"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 22,
      title: "Subset Sums",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("subset-sums2234"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking / Pick-NotPick",
      rating: 9,
      shortNote: "Find sums of all subsets.",
      longNote: "Use pick/not-pick recursion. Maintain a running sum.",
      tags: ["recursion", "backtracking"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 23,
      title: "Target Sum",
      platformName: "LeetCode",
      platformUrl: leetcode("target-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking / DP",
      rating: 9,
      shortNote: "Find number of ways to assign +/- to make target.",
      longNote: "Recurse adding or subtracting the current number. Use memoization.",
      tags: ["recursion", "dynamic-programming"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 24,
      title: "Perfect Sum Problem",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("perfect-sum-problem5633"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking / DP",
      rating: 8,
      shortNote: "Count subsets with a given sum.",
      longNote: "Recursion with target = target - arr[i] if picked. Handle 0s carefully if they exist.",
      tags: ["recursion", "dynamic-programming"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 25,
      title: "Combination Sum (Target Sum Repeated)",
      platformName: "LeetCode",
      platformUrl: leetcode("combination-sum"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking / Unbounded Knapsack",
      rating: 10,
      shortNote: "Find all combinations that sum to target, items can be repeated.",
      longNote: "When picking an item, don't move to the next index (allows repetition). Base cases: target==0 (found) or target<0 (invalid).",
      tags: ["recursion", "backtracking"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 26,
      title: "Permutations",
      platformName: "LeetCode",
      platformUrl: leetcode("permutations"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking",
      rating: 10,
      shortNote: "Generate all possible permutations of an array.",
      longNote: "Iterate and swap elements to generate permutations, then backtrack (swap back).",
      tags: ["recursion", "backtracking"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 27,
      title: "Permutations II",
      platformName: "LeetCode",
      platformUrl: leetcode("permutations-ii"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Backtracking",
      rating: 9,
      shortNote: "Generate all unique permutations of an array with duplicates.",
      longNote: "Sort the array. During backtracking, if i > index and nums[i] == nums[i-1], skip to avoid duplicates.",
      tags: ["recursion", "backtracking"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 28,
      title: "Climbing Stairs (Ways to Climb)",
      platformName: "LeetCode",
      platformUrl: leetcode("climbing-stairs"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Recursion / DP",
      rating: 8,
      shortNote: "Ways to climb stairs.",
      longNote: "Duplicate of Nth Stair. Simple Fibonacci.",
      tags: ["recursion", "dynamic-programming"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 29,
      title: "Tower of Hanoi",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("tower-of-hanoi-1587115621"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Classic Recursion",
      rating: 8,
      shortNote: "Solve the Tower of Hanoi puzzle.",
      longNote: "Move n-1 from src to aux, move 1 from src to dest, move n-1 from aux to dest.",
      tags: ["recursion"],
      priority: 8,
      isPinned: true,
    },
    {
      roadmapOrder: 30,
      title: "Predict the Winner",
      platformName: "LeetCode",
      platformUrl: leetcode("predict-the-winner"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Minimax",
      rating: 9,
      shortNote: "Determine if player 1 can win the game.",
      longNote: "Return max(nums[l] - solve(l+1, r), nums[r] - solve(l, r-1)). If result >= 0, P1 wins.",
      tags: ["recursion", "game-theory"],
      priority: 9,
      isPinned: false,
    },
    {
      roadmapOrder: 31,
      title: "Find the Winner of the Circular Game",
      platformName: "LeetCode",
      platformUrl: leetcode("find-the-winner-of-the-circular-game"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Josephus Problem",
      rating: 9,
      shortNote: "Find winner in Josephus game.",
      longNote: "solve(n, k) = (solve(n-1, k) + k) % n. Adjust for 1-based indexing.",
      tags: ["recursion", "math"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 32,
      title: "Rat in a Maze Problem - I",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("rat-in-a-maze-problem"),
      difficulty: "Hard",
      status: "unsolved",
      pattern: "Backtracking",
      rating: 10,
      shortNote: "Find all possible paths for a rat to reach the destination in a maze.",
      longNote: "Use DFS in 4 directions. Keep a visited array (or modify maze in-place) and backtrack after exploring.",
      tags: ["recursion", "backtracking"],
      priority: 10,
      isPinned: true,
    },
    {
      roadmapOrder: 33,
      title: "N-th Tribonacci Number",
      platformName: "LeetCode",
      platformUrl: leetcode("n-th-tribonacci-number"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Recursion / DP",
      rating: 7,
      shortNote: "Find Nth Tribonacci number.",
      longNote: "Return T(N-1) + T(N-2) + T(N-3). Base cases T(0)=0, T(1)=1, T(2)=1.",
      tags: ["recursion", "dynamic-programming"],
      priority: 7,
      isPinned: false,
    },
  ]),
  ...linkedListRoadmap([
    {
      roadmapOrder: 1,
      title: "Introduction to Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("introduction-to-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Linked List Traversal",
      rating: 5,
      shortNote: "Create a linked list from an array.",
      longNote: "Iterate over the array, create new nodes, and link them using next pointers.",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Middle of the Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("middle-of-the-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Slow & Fast Pointers",
      rating: 8,
      shortNote: "Find the middle node of a linked list.",
      longNote: "Use slow (1 step) and fast (2 steps) pointers. When fast reaches the end, slow is at the middle.",
      tags: ["linked-list", "two-pointers"],
      priority: 8,
      isPinned: true,
    },
    {
      roadmapOrder: 3,
      title: "Reverse Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("reverse-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Pointer Reversal",
      rating: 9,
      shortNote: "Reverse a singly linked list.",
      longNote: "Maintain prev, curr, and next pointers. Iterate and reverse curr.next to point to prev.",
      tags: ["linked-list"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 4,
      title: "Linked List Cycle",
      platformName: "LeetCode",
      platformUrl: leetcode("linked-list-cycle"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Slow & Fast Pointers",
      rating: 9,
      shortNote: "Detect cycle in a linked list.",
      longNote: "Floyd's cycle-finding algorithm: slow and fast pointers. If they meet, there's a cycle.",
      tags: ["linked-list", "two-pointers"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "Search in Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("search-in-linked-list-1664434326"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Linked List Traversal",
      rating: 5,
      shortNote: "Check if a key is present in the linked list.",
      longNote: "Iterate through the list. Return true if node.val == key.",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Merge Two Sorted Lists",
      platformName: "LeetCode",
      platformUrl: leetcode("merge-two-sorted-lists"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Dummy Node",
      rating: 9,
      shortNote: "Merge two sorted linked lists into one.",
      longNote: "Use a dummy head. Compare nodes from both lists and append the smaller one.",
      tags: ["linked-list", "two-pointers"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 7,
      title: "Remove Nth Node From End of List",
      platformName: "LeetCode",
      platformUrl: leetcode("remove-nth-node-from-end-of-list"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Slow & Fast Pointers",
      rating: 8,
      shortNote: "Remove the Nth node from the end of the list.",
      longNote: "Move fast pointer N steps ahead. Then move both slow and fast. When fast reaches end, slow.next is the node to remove.",
      tags: ["linked-list", "two-pointers"],
      priority: 8,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "Intersection of Two Linked Lists",
      platformName: "LeetCode",
      platformUrl: leetcode("intersection-of-two-linked-lists"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 8,
      shortNote: "Find the node at which the intersection of two singly linked lists begins.",
      longNote: "Two pointers, start at heads. When one reaches null, redirect it to the head of the other list. They will meet at the intersection or null.",
      tags: ["linked-list", "two-pointers"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Palindrome Linked List",
      platformName: "LeetCode",
      platformUrl: leetcode("palindrome-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Reverse Half List",
      rating: 8,
      shortNote: "Check if a linked list is a palindrome.",
      longNote: "Find middle (slow/fast), reverse the second half, and compare with the first half.",
      tags: ["linked-list", "two-pointers"],
      priority: 8,
      isPinned: false,
    },
  ]),
  ...doublyLinkedListRoadmap([
    {
      roadmapOrder: 1,
      title: "Introduction to Doubly Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("introduction-to-doubly-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "DLL Basics",
      rating: 5,
      shortNote: "Create a doubly linked list from an array.",
      longNote: "Iterate array, create nodes with prev and next pointers.",
      tags: ["linked-list", "doubly-linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Insert a node in Doubly Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Insert%20a%20node%20in%20Doubly%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "DLL Basics",
      rating: 6,
      shortNote: "Insert node at given position in DLL.",
      longNote: "Traverse to pos, update next and prev pointers of adjacent nodes.",
      tags: ["linked-list", "doubly-linked-list"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Delete node in Doubly Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("delete-node-in-doubly-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "DLL Basics",
      rating: 6,
      shortNote: "Delete node at given position in DLL.",
      longNote: "Traverse to pos, link prev and next nodes, handle head/tail edge cases.",
      tags: ["linked-list", "doubly-linked-list"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Reverse a Doubly Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("reverse-a-doubly-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Pointer Reversal",
      rating: 7,
      shortNote: "Reverse a doubly linked list.",
      longNote: "Swap next and prev for all nodes. Head becomes the last node processed.",
      tags: ["linked-list", "doubly-linked-list"],
      priority: 7,
      isPinned: true,
    },
    {
      roadmapOrder: 5,
      title: "Find pairs with given sum in doubly linked list",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("find-pairs-with-given-sum-in-doubly-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Two Pointers",
      rating: 7,
      shortNote: "Find pairs summing to target in sorted DLL.",
      longNote: "Left pointer at head, right pointer at tail. Move left if sum < target, right if sum > target.",
      tags: ["linked-list", "doubly-linked-list", "two-pointers"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 6,
      title: "Remove duplicates from a sorted doubly linked list",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("remove-duplicates-from-a-sorted-doubly-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 6,
      shortNote: "Remove duplicates from sorted DLL.",
      longNote: "Traverse list, if curr.data == curr.next.data, adjust pointers to skip next node.",
      tags: ["linked-list", "doubly-linked-list"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Design Browser History",
      platformName: "LeetCode",
      platformUrl: leetcode("design-browser-history"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Design / DLL",
      rating: 9,
      shortNote: "Design browser history using DLL.",
      longNote: "Maintain a DLL where each node is a URL, and a pointer to current page.",
      tags: ["linked-list", "doubly-linked-list", "design"],
      priority: 9,
      isPinned: true,
    },
    {
      roadmapOrder: 8,
      title: "LRU Cache",
      platformName: "LeetCode",
      platformUrl: leetcode("lru-cache"),
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Design / DLL + Hash Map",
      rating: 10,
      shortNote: "Implement LRU Cache.",
      longNote: "Use Hash Map for O(1) access and Doubly Linked List for O(1) removals/additions. Most recent at head, least recent at tail.",
      tags: ["linked-list", "doubly-linked-list", "design", "hash-table"],
      priority: 10,
      isPinned: true,
    },
  ]),
  ...circularLinkedListRoadmap([
    {
      roadmapOrder: 1,
      title: "Introduction to Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("circular-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "CLL Basics",
      rating: 5,
      shortNote: "Understand Circular Linked List.",
      longNote: "Last node points to the first node. Useful for round-robin scheduling.",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 2,
      title: "Circular Linked List Traversal",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("circular-linked-list-traversal"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "CLL Basics",
      rating: 5,
      shortNote: "Traverse and print CLL.",
      longNote: "Use a do-while loop to start at head and stop when current reaches head again.",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 3,
      title: "Check If Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Check%20If%20Circular%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 6,
      shortNote: "Check if a linked list is circular.",
      longNote: "Traverse from head. If node.next becomes null, it's not circular. If node.next == head, it is.",
      tags: ["linked-list"],
      priority: 6,
      isPinned: false,
    },
    {
      roadmapOrder: 4,
      title: "Count nodes in Circular linked list",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Count%20nodes%20in%20Circular%20linked%20list",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Traversal",
      rating: 4,
      shortNote: "Count total nodes in a circular linked list.",
      longNote: "Start from head, count++, move next until reaching head again.",
      tags: ["linked-list"],
      priority: 4,
      isPinned: false,
    },
    {
      roadmapOrder: 5,
      title: "Split a Circular Linked List into two halves",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("split-a-circular-linked-list-into-two-halves"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Slow & Fast Pointers",
      rating: 8,
      shortNote: "Split CLL into two circular lists.",
      longNote: "Find middle using slow/fast pointers. Break the loop and connect halves to themselves.",
      tags: ["linked-list", "two-pointers"],
      priority: 8,
      isPinned: true,
    },
    {
      roadmapOrder: 6,
      title: "Insert in a Sorted Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: gfg("sorted-insert-for-circular-linked-list"),
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Insertion",
      rating: 7,
      shortNote: "Insert a node into sorted CLL.",
      longNote: "Find correct position. Handle edge cases where new node becomes new head.",
      tags: ["linked-list"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 7,
      title: "Delete Node in a Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Delete%20Node%20in%20a%20Circular%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Deletion",
      rating: 7,
      shortNote: "Delete a node from CLL.",
      longNote: "Traverse to find node. Update prev.next. Special handling if deleting the head.",
      tags: ["linked-list"],
      priority: 7,
      isPinned: false,
    },
    {
      roadmapOrder: 8,
      title: "Exchange first and last nodes in Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Exchange%20first%20and%20last%20nodes%20in%20Circular%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Pointer manipulation",
      rating: 5,
      shortNote: "Swap head and tail nodes.",
      longNote: "Find tail. Swap data or adjust next pointers of tail, prev-to-tail, and head.",
      tags: ["linked-list"],
      priority: 5,
      isPinned: false,
    },
    {
      roadmapOrder: 9,
      title: "Reverse a Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Reverse%20a%20Circular%20Linked%20List",
      difficulty: "Easy",
      status: "unsolved",
      pattern: "Pointer Reversal",
      rating: 8,
      shortNote: "Reverse the pointers of a CLL.",
      longNote: "Standard reverse (prev, curr, next). After loop, update tail.next to new head.",
      tags: ["linked-list"],
      priority: 8,
      isPinned: false,
    },
    {
      roadmapOrder: 10,
      title: "Josephus Circle using Circular Linked List",
      platformName: "GeeksforGeeks",
      platformUrl: "https://www.google.com/search?q=%22GeeksforGeeks%22%20OR%20%22LeetCode%22%20Josephus%20Circle%20using%20Circular%20Linked%20List",
      difficulty: "Medium",
      status: "unsolved",
      pattern: "Simulation",
      rating: 8,
      shortNote: "Solve Josephus problem by simulating with CLL.",
      longNote: "Create CLL 1 to N. Traverse and delete every k-th node until one remains.",
      tags: ["linked-list", "math"],
      priority: 8,
      isPinned: true,
    },
  ]),
  ...stackRoadmap([
    { roadmapOrder: 1, title: "Implement Stack using Arrays", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/implement-stack-using-array/1", difficulty: "Easy", status: "unsolved", tags: ["stack"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 2, title: "Implement Stack using Queues", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/implement-stack-using-queues/", difficulty: "Easy", status: "unsolved", tags: ["stack"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 3, title: "Valid Parentheses", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/valid-parentheses/", difficulty: "Easy", status: "unsolved", tags: ["stack"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 4, title: "Min Stack", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/min-stack/", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 8, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 5, title: "Minimum Add to Make Parentheses Valid", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 6, title: "Remove Invalid Parentheses", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/remove-invalid-parentheses/", difficulty: "Hard", status: "unsolved", tags: ["stack"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 7, title: "Backspace String Compare", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/backspace-string-compare/", difficulty: "Easy", status: "unsolved", tags: ["stack"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 8, title: "The Celebrity Problem", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/the-celebrity-problem/1", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 9, title: "Next Greater Element / Smaller Element", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 10, title: "Smallest number on left", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/smallest-number-on-left3403/1", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 11, title: "Next Greater Element II", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/next-greater-element-ii/", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 12, title: "Stock span problem", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/stock-span-problem-1587115621/1", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 13, title: "Largest Rectangle in Histogram", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/", difficulty: "Hard", status: "unsolved", tags: ["stack"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 14, title: "Maximal Rectangle", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/maximal-rectangle/", difficulty: "Hard", status: "unsolved", tags: ["stack"], priority: 10, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 15, title: "Get minimum element from stack", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/get-minimum-element-from-stack/1", difficulty: "Medium", status: "unsolved", tags: ["stack"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 16, title: "Max rectangle", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/max-rectangle/1", difficulty: "Hard", status: "unsolved", tags: ["stack"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 17, title: "Implement two stacks in an array", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/implement-two-stacks-in-an-array/1", difficulty: "Easy", status: "unsolved", tags: ["stack"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 18, title: "N Stack In An Array", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/n-stack-in-an-array/1", difficulty: "Hard", status: "unsolved", tags: ["stack"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
  ]),
  ...queueRoadmap([
    { roadmapOrder: 1, title: "Implement Queue using Linked List", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/implement-queue-using-linked-list/1", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 2, title: "Print Queue", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/print-queue/1", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 4, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 3, title: "Queue Reversal", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/queue-reversal/1", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 4, title: "Reverse First K elements of Queue", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 5, title: "Time Needed to Buy Tickets", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/time-needed-to-buy-tickets/", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 6, title: "Implement Queue using Stacks", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/implement-queue-using-stacks/", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 8, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 7, title: "Implement Stack using Queues", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/implement-stack-using-queues/", difficulty: "Easy", status: "unsolved", tags: ["queue"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
  ]),
  ...treeRoadmap([
    { roadmapOrder: 1, title: "Tree Traversals", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/tree-traversals/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 2, title: "Level order traversal", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/level-order-traversal/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 3, title: "Size of Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/size-of-binary-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 4, title: "Sum of Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/sum-of-binary-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 5, title: "Count Leaves in Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/count-leaves-in-binary-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 6, title: "Count Non-Leaf Nodes in Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/count-non-leaf-nodes-in-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 7, title: "Height of Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/height-of-binary-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 8, title: "Largest value in each level", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/largest-value-in-each-level/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 9, title: "Determine if Two Trees are Identical", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 10, title: "Mirror Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/mirror-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 11, title: "Check for Balanced Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/check-for-balanced-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 12, title: "Level order traversal in spiral form", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 13, title: "Cousins in Binary Tree", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/cousins-in-binary-tree/", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 14, title: "Left / Right / Top / Bottom View", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1", difficulty: "Easy", status: "unsolved", tags: ["tree"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 15, title: "Construct Tree from Preorder and Inorder", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/construct-tree-1/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 16, title: "Construct Tree from Postorder and Inorder", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/tree-from-postorder-and-inorder/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 9, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 17, title: "Vertical Traversal of Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/print-a-binary-tree-in-vertical-order/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 18, title: "Diagonal Traversal of Binary Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/diagonal-traversal-of-binary-tree/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 19, title: "Boundary Traversal of binary tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 20, title: "Morris Traversal", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/inorder-traversal-without-recursion-and-without-stack/1", difficulty: "Hard", status: "unsolved", tags: ["tree"], priority: 9, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 21, title: "Flatten binary tree to linked list", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/flatten-binary-tree-to-linked-list/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 22, title: "Burning Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/burning-tree/1", difficulty: "Hard", status: "unsolved", tags: ["tree"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 23, title: "Maximum path sum from any node", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1", difficulty: "Medium", status: "unsolved", tags: ["tree"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
  ]),
  ...bstRoadmap([
    { roadmapOrder: 1, title: "Binary Search Tree", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/binary-search-trees/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 2, title: "Check for BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/check-for-bst/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 3, title: "Minimum element in BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/minimum-element-in-bst/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 4, title: "K-th Smallest Element in BST", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", difficulty: "Medium", status: "unsolved", tags: ["bst"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 5, title: "Kth largest element in BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/kth-largest-element-in-bst/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 6, title: "Array to BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/array-to-bst4443/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 7, title: "Construct BST from Preorder Traversal", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/", difficulty: "Medium", status: "unsolved", tags: ["bst"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 8, title: "Preorder Traversal and BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/preorder-traversal-and-bst4006/1", difficulty: "Medium", status: "unsolved", tags: ["bst"], priority: 8, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 9, title: "Lowest Common Ancestor in a BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 10, title: "Print BST elements in given range", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/print-bst-elements-in-given-range/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 11, title: "Common Nodes in two BSTs", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/common-nodes-in-bst/1", difficulty: "Easy", status: "unsolved", tags: ["bst"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 12, title: "Convert Sorted List to Binary Search Tree", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/", difficulty: "Medium", status: "unsolved", tags: ["bst", "linked-list"], priority: 8, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 13, title: "Merge two BST 's", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/merge-two-bst-s/1", difficulty: "Hard", status: "unsolved", tags: ["bst"], priority: 9, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 14, title: "Recover Binary Search Tree", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/recover-binary-search-tree/", difficulty: "Medium", status: "unsolved", tags: ["bst"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 15, title: "Largest BST", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/largest-bst/1", difficulty: "Hard", status: "unsolved", tags: ["bst"], priority: 10, isPinned: true, shortNote: "", longNote: "" },
  ]),
  ...heapRoadmap([
    { roadmapOrder: 1, title: "Build Heap / Heap Sort", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/heap-sort/1", difficulty: "Medium", status: "unsolved", tags: ["heap"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 2, title: "Height of Heap", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/height-of-heap/1", difficulty: "Easy", status: "unsolved", tags: ["heap"], priority: 5, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 3, title: "Minimum Cost of ropes", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/minimum-cost-of-ropes-1587115620/1", difficulty: "Easy", status: "unsolved", tags: ["heap", "greedy"], priority: 8, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 4, title: "Magician and Chocolates", platformName: "GeeksforGeeks", platformUrl: "https://www.geeksforgeeks.org/problems/magician-and-chocolates/1", difficulty: "Easy", status: "unsolved", tags: ["heap"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 5, title: "Last Stone Weight", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/last-stone-weight/", difficulty: "Easy", status: "unsolved", tags: ["heap"], priority: 7, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 6, title: "Take Gifts From the Richest Pile", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/take-gifts-from-the-richest-pile/", difficulty: "Easy", status: "unsolved", tags: ["heap"], priority: 6, isPinned: false, shortNote: "", longNote: "" },
    { roadmapOrder: 7, title: "IPO", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/ipo/", difficulty: "Hard", status: "unsolved", tags: ["heap", "greedy"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
    { roadmapOrder: 8, title: "Kth Smallest Element in a Sorted Matrix", platformName: "LeetCode", platformUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", difficulty: "Medium", status: "unsolved", tags: ["heap", "binary-search"], priority: 9, isPinned: true, shortNote: "", longNote: "" },
  ]),
];

