import type { TopicSeed } from "./types.js";

export const topicSeeds: TopicSeed[] = [
  {
    name: "Foundation",
    slug: "foundation",
    order: 1,
    targetCount: 46,
    description: "Time complexity, STL, math, recursion, and core problem solving basics.",
    accent: "#7dd3fc",
  },
  {
    name: "Arrays",
    slug: "arrays",
    order: 2,
    targetCount: 45,
    description: "Classic array problems, patterns, and foundational interview questions.",
    accent: "#fda4af",
  },
  {
    name: "Strings",
    slug: "strings",
    order: 3,
    targetCount: 35,
    description: "String manipulation, parsing, frequency tricks, and pattern matching.",
    accent: "#86efac",
  },
  {
    name: "Hashing",
    slug: "hashing",
    order: 4,
    targetCount: 20,
    description: "Maps, sets, frequency tables, and lookup-based optimization.",
    accent: "#f9a8d4",
  },
  {
    name: "Two Pointers",
    slug: "two-pointers",
    order: 5,
    targetCount: 20,
    description: "Left-right scanning, pair matching, and range optimization.",
    accent: "#fdba74",
  },
  {
    name: "Sliding Window",
    slug: "sliding-window",
    order: 6,
    targetCount: 25,
    description: "Window-based counting, subarray optimization, and frequency updates.",
    accent: "#c4b5fd",
  },
  {
    name: "Binary Search",
    slug: "binary-search",
    order: 7,
    targetCount: 35,
    description: "Binary search on arrays, answer space, and monotonic conditions.",
    accent: "#93c5fd",
  },
  {
    name: "Linked List",
    slug: "linked-list",
    order: 8,
    targetCount: 36,
    description: "Single and doubly linked list patterns, reversals, and cycle logic.",
    accent: "#67e8f9",
  },
  {
    name: "Stack",
    slug: "stack",
    order: 9,
    targetCount: 30,
    description: "Stack usage, monotonic stack, parsing, and expression logic.",
    accent: "#fcd34d",
  },
  {
    name: "Queue",
    slug: "queue",
    order: 10,
    targetCount: 15,
    description: "Queue patterns, deque usage, and task scheduling ideas.",
    accent: "#a7f3d0",
  },
  {
    name: "Trees",
    slug: "trees",
    order: 11,
    targetCount: 60,
    description: "Traversals, recursion, diameter, views, and tree DP basics.",
    accent: "#fde68a",
  },
  {
    name: "Binary Search Tree (BST)",
    slug: "bst",
    order: 12,
    targetCount: 25,
    description: "BST search, insertion, deletion, and validation patterns.",
    accent: "#fca5a5",
  },
  {
    name: "Heap / Priority Queue",
    slug: "heap-priority-queue",
    order: 13,
    targetCount: 25,
    description: "Top-k, selection, merging, and priority-driven decisions.",
    accent: "#c084fc",
  },
  {
    name: "Graph",
    slug: "graph",
    order: 14,
    targetCount: 70,
    description: "Traversal, shortest path, topological sorting, and DSU.",
    accent: "#60a5fa",
  },
  {
    name: "Greedy",
    slug: "greedy",
    order: 15,
    targetCount: 35,
    description: "Local choice reasoning, scheduling, and exchange arguments.",
    accent: "#34d399",
  },
  {
    name: "Backtracking",
    slug: "backtracking",
    order: 16,
    targetCount: 25,
    description: "Enumerating possibilities with pruning and recursion trees.",
    accent: "#fb7185",
  },
  {
    name: "Trie",
    slug: "trie",
    order: 17,
    targetCount: 15,
    description: "Prefix trees, word search, and dictionary-style lookups.",
    accent: "#22c55e",
  },
  {
    name: "Dynamic Programming",
    slug: "dynamic-programming",
    order: 18,
    targetCount: 80,
    description: "Recurrence patterns, memoization, tabulation, and optimization.",
    accent: "#818cf8",
  },
  {
    name: "Bit Manipulation",
    slug: "bit-manipulation",
    order: 19,
    targetCount: 25,
    description: "Bit tricks, masks, subset logic, and XOR reasoning.",
    accent: "#38bdf8",
  },
  {
    name: "Segment Tree & Fenwick Tree",
    slug: "segment-tree-fenwick-tree",
    order: 20,
    targetCount: 15,
    description: "Range queries, updates, and advanced logarithmic structures.",
    accent: "#f472b6",
  },
];

